### ISSUE TITLE
How to Use this Driver?

### ISSUE THREAD

**Issue by wuchuguang** [erlangbureau/jamdb_oracle#1]
thank you

**Comment by kostyushkin** [comment]
It is still in early beta. So we didn't write documentation.
But it is very similar to this: https://github.com/erlangbureau/jamdb_sybase/blob/master/README.md

**Comment by wuchuguang** [comment]
thx,
i try run it,
but cant run.

{badmatch,<<"@69CE65768E59574A04B2240D7B1CB0D561650669686944A9EEA4F23B60C1DBB8 18ACDDFB95BD89695D0564D53DEBA0D8"...>>}
     in function  jamdb_oracle_tns_decoder:decode_next/1 (src/jamdb_oracle_tns_decoder.erl, line 255)
     in call from jamdb_oracle_tns_decoder:decode_keyval/3 (src/jamdb_oracle_tns_decoder.erl, line 389)
     in call from jamdb_oracle_tns_decoder:decode_token/2 (src/jamdb_oracle_tns_decoder.erl, line 68)
     in call from jamdb_oracle_conn:handle_login_resp/2 (src/jamdb_oracle_conn.erl, line 139)
     in call from jamdb_oracle_conn:connect/2 (src/jamdb_oracle_conn.erl, line 73)


---------------------------------------------------------------------------------------------------------------------
decode_next(<<Len,Rest/bits>>) ->
    io:format("len ~w data ~w~n",[Len, erlang:bit_size(Rest)]),
    <<_Data:Len/binary,Rest2/bits>> = Rest,%%this is 255 line
    Rest2.

**Comment by wuchuguang** [comment]
>application:start(jamdb_oracle).

>jamdb_oracle:start_link([{host, "192.168.1.231"}, {user, "test"}, {password, "test"}, {lib_name,"hhjj_bsw"},{sid,"hhjj_bsw"}]).

"hhjj_bsw" is my database name

**Comment by kostyushkin** [comment]
I'll see when i have time and write when the result will be

**Comment by wuchuguang** [comment]
thx

**Comment by kostyushkin** [comment]
Try now
