### ISSUE TITLE
I can not connect

### ISSUE THREAD

**Issue by braulio** [erlangbureau/jamdb_oracle#100]
Hello! 
I can not connect. I'm using Ecto with Jamdb. I always get the error message below;

[error] Jamdb.Oracle (#PID<0.605.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, :closed}
[error] Jamdb.Oracle (#PID<0.599.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, :closed}
[error] Jamdb.Oracle (#PID<0.602.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, :closed}
[error] Jamdb.Oracle (#PID<0.614.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, :closed}
[error] Jamdb.Oracle (#PID<0.608.0>) failed to connect: ** (DBConnection.ConnectionError) {:socket, :closed}

What could be happening?

Thx.

**Comment by vstavskyi** [comment]
Check IP , PORT, SID or Service Name once more.
Use Wireshark with filter TNS to check network packets.
Also try patch from this [reply](https://github.com/erlangbureau/jamdb_oracle/issues/93#issuecomment-830756309).

**Comment by braulio** [comment]
we checked everything and it's correct: IP, PORT etc. The only thing different is the database name: 

database: "THCI.br1.ocm.s066055.oraclecloudatcustomer.com"

Thx.

**Comment by vstavskyi** [comment]
Maybe this name is not resolved on your client machine.

Let's check socket creation.

Eshell V10.7  (abort with ^G)
1> gen_tcp:connect("THCI.br1.ocm.s066055.oraclecloudatcustomer.com", 1521, []).
{ok,#Port<0.6>}

Let's try using parameter **description**. 
For socket creation module gen_tcp will use parameters **hostname** and **port**.
Server Listener will use name from description.

....
  hostname: "THCI",
  port: 1521,
....
  parameters: [description: "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=THCI.br1.ocm.s066055.oraclecloudatcustomer.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))"]

**Comment by vstavskyi** [comment]
Try to capture packets with Wireshark.
Maybe listener makes redirection to different ip/name and port.

**Comment by braulio** [comment]
See: "THCI.br1.ocm.s066055.oraclecloudatcustomer.com" is the name of the database.

See the TNSNAMES used by sqldeveloper:

(DESCRIPTION =
   (ADDRESS_LIST =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.10.1.191)(PORT = 1521))
    (ADDRESS = (PROTOCOL = TCP)(HOST = 10.10.1.191)(PORT = 1521))
   )
    (CONNECT_DATE =
      (SERVER = DEDICATED)
      (SERVICE_NAME = THCI.br1.ocm.s066055.oraclecloudatcustomer.com)
      (FAILOVER_MODE =
        (TYPE = select)
        (METHOD = basic)
      )
    )
  )

With sqldeveloper, everything works normally.

**Comment by vstavskyi** [comment]
Sorry, I got it.

...
hostname: "10.10.1.191",
...

Try gen_tcp:connect("10.10.1.191", 1521, []).

**Comment by vstavskyi** [comment]
Modify  jamdb_oracle_tns_decoder.erl to print packets.

decode_packet(<<PacketSize:16, _PacketFlags:16, ?TNS_DATA, _Flags:8, 0:16, _DataFlags:16, Rest/bits>> = Data, Length) ->
    io:format("~ts~n", [Data]),
...

decode_packet(<<_PacketSize:16, _PacketFlags:16, ?TNS_REDIRECT, _Flags:8, 0:16, _Length:16, Rest/bits>> = Data, Length) ->
    io:format("~ts~n", [Data]),
...

decode_packet(<<PacketSize:16, _PacketFlags:16, Type, _Flags:8, 0:16, Rest/bits>> = Data, _Length) ->
    io:format("~ts~n", [Data]),
...
