### ISSUE TITLE
decode_chr issue

### ISSUE THREAD

**Issue by aby2503** [erlangbureau/jamdb_oracle#101]
Good day. 
On the actual version of adapter I'm getting `Jamdb.Oracle.Error`
`[{:jamdb_oracle_tns_decoder, :decode_chr, 2, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 518]}, {:jamdb_oracle_tns_decoder, :decode_clob, 1, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 677]}, {:jamdb_oracle_tns_decoder, :decode_data, 2, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 407]}, {:jamdb_oracle_tns_decoder, :decode_rxd, 6, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 344]}, {:jamdb_oracle_tns_decoder, :decode_token, 3, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 184]}, {:jamdb_oracle_conn, :handle_resp, 3, [file: 'src/jamdb_oracle_conn.erl', line: 254]}, {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 54]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}]`

Could you please advise smth

**Comment by vstavskyi** [comment]
clob issue #65 
try dbms_lob.substr
