### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by braulio** [erlangbureau/jamdb_oracle#104]
Unexpectedly we are getting this erro.

Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [error] GenServer #PID<0.815.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, <<23, 2, 1, 6, 6, 50, 48, 50, 55, 51, 49, 4, 1, 5, 1, 4>>}
    (jamdb_oracle 0.4.11) lib/jamdb_oracle.ex:214: Jamdb.Oracle.checkout/1
    (db_connection 2.4.1) lib/db_connection/connection.ex:239: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:connected, #Reference<0.2335094046.3174301701.194002>}}
State: {Jamdb.Oracle, %Jamdb.Oracle{cursors: nil, mode: :idle, pid: #PID<0.831.0>}}

what has changed??

Thx.

**Comment by vstavskyi** [comment]
Only db_connection was changed.

**Comment by braulio** [comment]
We delete all dependencies and compile:

mix compile
==> connection
Compiling 1 file (.ex)
Generated connection app
===> Analyzing applications...
===> Compiling telemetry_poller
==> gettext
Compiling 1 file (.erl)
Compiling 20 files (.ex)
Generated gettext app
===> Analyzing applications...
===> Compiling ranch
===> Analyzing applications...
===> Compiling telemetry
==> telemetry_metrics
Compiling 7 files (.ex)
Generated telemetry_metrics app
==> decimal
Compiling 4 files (.ex)
Generated decimal app
==> jason
Compiling 8 files (.ex)
Generated jason app
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> ecto
Compiling 56 files (.ex)
Generated ecto app
==> ecto_sql
Compiling 26 files (.ex)
Generated ecto_sql app
==> jamdb_oracle
Compiling 5 files (.erl)
Compiling 3 files (.ex)
warning: function returning/2 is unused
  lib/jamdb_oracle_query.ex:537

warning: module attribute @impl was not set for function update_all/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:125: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function update/5 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:128: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function to_constraints/2 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:133: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function table_exists_query/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:130: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function insert/7 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:127: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function execute_ddl/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:131: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function delete_all/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:126: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function delete/4 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:129: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function ddl_logs/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:132: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: module attribute @impl was not set for function all/1 callback (specified in Ecto.Adapters.SQL.Connection). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/jamdb_oracle_ecto.ex:124: Ecto.Adapters.Jamdb.Oracle.Connection (module)

warning: got "@impl true" for function checkin/1 but no behaviour specifies such callback. The known callbacks are:

  * DBConnection.checkout/1 (function)
  * DBConnection.connect/1 (function)
  * DBConnection.disconnect/2 (function)
  * DBConnection.handle_begin/2 (function)
  * DBConnection.handle_close/3 (function)
  * DBConnection.handle_commit/2 (function)
  * DBConnection.handle_deallocate/4 (function)
  * DBConnection.handle_declare/4 (function)
  * DBConnection.handle_execute/4 (function)
  * DBConnection.handle_fetch/4 (function)
  * DBConnection.handle_prepare/3 (function)
  * DBConnection.handle_rollback/2 (function)
  * DBConnection.handle_status/2 (function)
  * DBConnection.ping/1 (function)

  lib/jamdb_oracle.ex:208: Jamdb.Oracle (module)

Can you fix??


Thx.

**Comment by vstavskyi** [comment]
Done.
