### ISSUE TITLE
cannot compile jamdb_oracle

### ISSUE THREAD

**Issue by elsbiet** [erlangbureau/jamdb_oracle#106]
executing rebar3 compile produces

===> Verifying dependencies...
===> Dep myxql has invalid version ~> 0.4.0 or ~> 0.5.0

what can i do to get around this issue?

thanks for your answer

**Comment by vstavskyi** [comment]
{:myxql, "~> 0.4.0 or ~> 0.5.0", optional: true}   line 96 in ecto_sql/[mix.exs](https://github.com/elixir-ecto/ecto_sql/blob/7bef2cf7ea016f2311241c6a213bdb3284b62fda/mix.exs#L96)

rebar3 app has this error, try mix app instead.

or make local deps of all packages and edit all mix.exs files.

**Comment by elsbiet** [comment]
thanks
