### ISSUE TITLE
How I add millisecond in naive_datetime or utn_datetime type

### ISSUE THREAD

**Issue by thachtan** [erlangbureau/jamdb_oracle#107]
I have some problem with save time with millisecond. How I save it in Oracle with jamdb_oracle

**Comment by vstavskyi** [comment]
example 

Ecto.Adapters.SQL.query(YourApp.Repo, "update tabl set tim=:1", [{{2022,2,24}, {4,0,0,123000}}])

**Comment by vstavskyi** [comment]
Recommend using functions like TO_DATE etc.

**Comment by thachtan** [comment]
Thank you for this example with query.

But I want to set millisecond with type :naive_datetime_usec or :utc_datetime_usec in change set and timestamps.

**Comment by vstavskyi** [comment]
try now
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/49a5bacee5479afb3b3777b2860c2d707c7c8894)

**Comment by thachtan** [comment]
It works!!! Thanks you for take time to help this issue ^^
