### ISSUE TITLE
can not be config to run mix ecto.migrate

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#11]
mix.exs
def application do
    [mod: {HelloPhoenix, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext, :jamdb_oracle,
                    :phoenix_ecto]]
  end
defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:jamdb_oracle, "~> 0.0.5"},
     {:cowboy, "~> 1.0"}]
  end

dev.exs
config :hello_phoenix, HelloPhoenix.Repo,
  name: HelloPhoenix.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  port: 1521,
  username: "username",
  password: "password",
  database: ":devdb1",
  hostname: "mydblocal.com",
  pool_size: 10,
  pool: DBConnection.Poolboy

errors when run mix ecto.migrate
Generated hello_phoenix app
** (MatchError) no match of right hand side value: {:error, {Jamdb.Oracle, {'no such file or directory', 'Elixir.Jamdb.Oracle.app'}}}
    (ecto) lib/mix/ecto.ex:84: Mix.Ecto.ensure_started/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:72: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2

any help?

**Comment by vstavskyi** [comment]
Sorry, the migration feature isn't implemented, it's a very complicated task . Any Orаcle dba would recommend you look at [Oracle offers](http://www.oracle.com/technetwork/database/migration/index.html).
Did you prepare migration file in priv/repo/migrations with ecto.gen.migration or by hand?

**Comment by yukilau99** [comment]
Hi Vstavskyi, thanks for your reply, the migration file was generated automatically after run the command: mix phoenix.gen.html

**Comment by vstavskyi** [comment]
Ecto.Repo callbacks like all, one, insert. update, delete were tested in my simple elixir application. 
You can also call function Ecto.Adapters.SQL.query on existing database with any statement, for example, CREATE TABLE.

**Comment by yukilau99** [comment]
iex(5)> Repo.all Tag
[debug] QUERY ERROR source="tags" db=16.0ms
SELECT t0.tagid, t0.tagname FROM tags t0 []
** (ArgumentError) cannot load `'All Tablet Laptop Parts_12-16-15'` as type :string for :tagname in schema HelloPhoenix.Tag
             (ecto) lib/ecto/schema.ex:1418: Ecto.Schema.load!/5
             (ecto) lib/ecto/schema.ex:1399: Ecto.Schema.__load__/5
             (ecto) lib/ecto/schema.ex:1371: Ecto.Schema.__load__/6
             (ecto) lib/ecto/adapters/sql.ex:582: anonymous fn/4 in Ecto.Adapters.SQL.process_row/4
           (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
             (ecto) lib/ecto/adapters/sql.ex:579: Ecto.Adapters.SQL.process_row/4
           (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
     (jamdb_oracle) lib/jamdb_oracle.ex:188: DBConnection.Query.Jamdb.Oracle.Query.decode/3
    (db_connection) lib/db_connection.ex:1011: DBConnection.decode/6
     (jamdb_oracle) lib/jamdb_oracle_ecto.ex:90: Ecto.Adapters.Jamdb.Oracle.Connection.prepare_execute/5
             (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
             (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
             (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
             (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4

Seems could load data from Oracle, but coding or parsing exception? any suggestion?

**Comment by vstavskyi** [comment]
Fix decode string and datetime
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/09d1f4a9e0833d3e947cc514ae3ef68836db4f69)

**Comment by yukilau99** [comment]
Using this fix could query from DB, but exception show if I run Repo.all again.

iex(3)> Repo.all Tag
[debug] QUERY OK source="tags" db=0.0ms decode=15.0ms
SELECT t0.tagid, t0.tagname FROM tags t0 []
[%HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">, tagid: 14,
  tagname: "All Tablet Laptop Parts_12-16-15"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
  tagid: 10002, tagname: "test tag452"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
  tagid: 10004, tagname: "test tag42"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">, tagid: 16,
  tagname: "All Flex_1-13-16gg"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
  tagid: 10003, tagname: "test tag31"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">, tagid: 13,
  tagname: "All LCD_12-16-15"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
  tagid: 10001, tagname: "test tag23"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
  tagid: 10005, tagname: "test tag1"},
 %HelloPhoenix.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">, tagid: 15,
  tagname: "All Phone Accessories_12-16-15"}]
iex(4)> Repo.all Tag
** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2
           (logger) lib/logger/utils.ex:20: Logger.Utils.truncate_n(%Jamdb.Oracle.Query{statement: "SELECT t0.tagid, t0.tagname FROM tags t0"}, 8060)
           (logger) lib/logger/utils.ex:49: Logger.Utils.truncate_n_list/3
           (logger) lib/logger/utils.ex:16: Logger.Utils.truncate/2
           (logger) lib/logger.ex:507: Logger.bare_log/3
             (ecto) lib/ecto/log_entry.ex:41: Ecto.LogEntry.log/1
    (db_connection) lib/db_connection.ex:1178: DBConnection.log/6
     (jamdb_oracle) lib/jamdb_oracle_ecto.ex:82: Ecto.Adapters.Jamdb.Oracle.Connection.execute/4
             (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
             (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7
             (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
             (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
iex(4)> [error] GenServer #PID<0.232.0> terminating
** (DBConnection.ConnectionError) client #PID<0.372.0> stopped: ** (Protocol.UndefinedError) protocol List.Chars not implemented for %Jamdb.Oracle.Query{statement: "SELECT t0.tagid, t0.tagname FROM tags t0"}
    (elixir) lib/list/chars.ex:1: List.Chars.impl_for!/1
    (elixir) lib/list/chars.ex:12: List.Chars.to_charlist/1
    (jamdb_oracle) lib/jamdb_oracle.ex:95: Jamdb.Oracle.handle_execute/4
    (db_connection) lib/db_connection.ex:958: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:1078: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:82: Ecto.Adapters.Jamdb.Oracle.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:224: :elixir.erl_eval/3
    (elixir) src/elixir.erl:212: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:182: IEx.Evaluator.handle_eval/6
    (iex) lib/iex/evaluator.ex:175: IEx.Evaluator.do_eval/4
    (iex) lib/iex/evaluator.ex:155: IEx.Evaluator.eval/4
    (iex) lib/iex/evaluator.ex:61: IEx.Evaluator.loop/3

    (db_connection) lib/db_connection/connection.ex:243: DBConnection.Connection.handle_cast/2

**Comment by vstavskyi** [comment]
Please, try now
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/73f143d6120134539130265e43755cde6f43e3e7)

**Comment by yukilau99** [comment]
Errors in this commit:

** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2
           (logger) lib/logger/utils.ex:20: Logger.Utils.truncate_n(%Jamdb.Oracle.Query{statement: "SELECT t0.tagid, t0.tagname FROM tags t0"}, 8064)
           (logger) lib/logger/utils.ex:49: Logger.Utils.truncate_n_list/3
           (logger) lib/logger/utils.ex:16: Logger.Utils.truncate/2
           (logger) lib/logger.ex:507: Logger.bare_log/3
             (ecto) lib/ecto/log_entry.ex:41: Ecto.LogEntry.log/1
    (db_connection) lib/db_connection.ex:1178: DBConnection.log/6
     (jamdb_oracle) lib/jamdb_oracle_ecto.ex:82: Ecto.Adapters.Jamdb.Oracle.Connection.execute/4
             (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
             (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.execute_or_reset/7
             (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
             (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4

**Comment by yukilau99** [comment]
Do you implement ecto.preload ?

**Comment by vstavskyi** [comment]
preload is not tested, but I added handle_prepare and fixed handle_execute error.
[revert](https://github.com/erlangbureau/jamdb_oracle/commit/e613615741b64ea277fe46b173cbddd04702096a)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/58c8d17e6d7570f531f13b7c470a80f4897b51e7)
