### ISSUE TITLE
Oracle has released a Python 'Thin' driver that connects directly to Oracle Database

### ISSUE THREAD

**Issue by cjbj** [erlangbureau/jamdb_oracle#112]
We (Oracle) just pushed a major release of our Python driver for Oracle Database.  It has a new name: [python-oracledb](https://oracle.github.io/python-oracledb/).  You might be interested in its 'Thin' mode code, available under an open source licence.  See the [repo](https://github.com/oracle/python-oracledb), in particular see https://github.com/oracle/python-oracledb/tree/main/src/oracledb/impl/thin which implements direct connection to Oracle Database.

**Comment by lemenkov** [comment]
@cjbj that's absolutely awesome news!

**Comment by vstavskyi** [comment]
Thank you, it's very interesting!
I'll dig later.
