### ISSUE TITLE
Repo.insert_all support in jamdb_oracle driver.

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#113]
@vstavskyi 

Is it possible to use the function

Repo.insert_all(table_name, chunk_data)

using this jamdb_oracle driver?

I have a use case where I have to bulk load data into Oracle database from my Elixir application. Appreciate your help with this.

Thanks... Muralee

**Comment by vasumur** [comment]
Attempted bulk insert code provided in #74 , but while passing nil value as a value, the code is failing with the below error.

Also the 2nd value "hello" is stored in the database as 68656C6C6F

** (DBConnection.ConnectionError) :function_clause
    (db_connection 2.4.2) lib/db_connection.ex:674: DBConnection.execute!/4

The code snippet is below.
`
   %{pid: pool} = Ecto.Adapter.lookup_meta(Everest.Repo)

    uuid =
      Enum.map(1..999, fn _x ->
        [String.replace(Ecto.UUID.generate(), "-", ""), "hello", nil]
      end)

    Logger.info("uuid = #{inspect(uuid)}")

    DBConnection.transaction(pool, fn conn ->
      query = %Jamdb.Oracle.Query{
        statement: "insert into erl8 (uuid, title, x ) values (:1, :2, :3)",
        batch: true
      }

      query = DBConnection.prepare!(conn, query)

      try do
        DBConnection.execute!(conn, query, uuid)
      after
        DBConnection.close(conn, query)
      end
    end)
    |> IO.inspect()
`

**Comment by vstavskyi** [comment]
Update batching is implemeted only in [erl](https://github.com/erlangbureau/jamdb_oracle/blob/3ad6330d7c4b541a319baea8beed8840ba1ecbd4/src/jamdb_oracle_conn.erl#L101)

Statement must be a tuple {batch, Sql, ParamList}

`{:batch, "insert into tabl values (:1, :2, :3)", [[1, 2, 3],[4, 5, 6],[7, 8, 9]]}`

**Comment by vasumur** [comment]
@vstavskyi 

Appreciate if you could provide an example from Elixir on how to invoke this. Thanks

**Comment by vasumur** [comment]
Tried something like below. But getting the below error. Apologies I haven't tried calling Erlang functions before. Appreciate any help you could provide.

** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.sql_query/2

`
%{pid: conn} = Ecto.Adapter.lookup_meta(Everest.Repo)

:jamdb_oracle_conn.sql_query(conn, {:batch, "insert into tabl values (:1, :2, :3)", [[1, 2, 3],[4, 5, 6],[7, 8, 9]]})
`

**Comment by vstavskyi** [comment]
Parameters Encoding is missing when DBConnection is used directly.

nil in jamdb_oracle.ex#[L296](https://github.com/erlangbureau/jamdb_oracle/blob/3ad6330d7c4b541a319baea8beed8840ba1ecbd4/lib/jamdb_oracle.ex#L296)

string in jamdb_oracle.ex#[L314](https://github.com/erlangbureau/jamdb_oracle/blob/3ad6330d7c4b541a319baea8beed8840ba1ecbd4/lib/jamdb_oracle.ex#L314)

Try
```
uuid =
  Enum.map(1..999, fn _x ->
    [String.replace(Ecto.UUID.generate(), "-", "") |> Jamdb.Oracle.to_list,
     "hello"  |> Jamdb.Oracle.to_list, 
     :null]
  end)
```

**Comment by vstavskyi** [comment]
I forgot about batch option :)
But it's working.

**Comment by vstavskyi** [comment]
Try 

```
uuid =
  Enum.map(1..999, fn _x ->
   DBConnection.Query.encode(
        %Jamdb.Oracle.Query{},  
        [String.replace(Ecto.UUID.generate(), "-", ""), "hello", nil], 
        [])
  end)
```

**Comment by vasumur** [comment]
Not sure I am following you.

In my case I am preparing the statement using the below statement.

           insert_stmt =
              DBConnection.prepare!(conn, %Jamdb.Oracle.Query{
                statement:
                  "INSERT INTO #{table_name} (#{column_names_str}) VALUES (#{bind_variables})",
                batch: true
              })

And then passing data to the prepared statement as below.

DBConnection.execute!(conn, insert_stmt, tx_data)

The above tx_data is already using the earlier encoding logic using  Jamdb.Oracle.to_list() etc.

Are you saying I should use this encoding on the data as well asd encoding the Jamdb.Oracle.Query?

**Comment by vstavskyi** [comment]
Just use DBConnection.Query.encode for all parameters.  
You can forget about Jamdb.Oracle.to_list for each of the parameters.

**Comment by vasumur** [comment]
Thanks @vstavskyi.
