### ISSUE TITLE
Oracle cloud database

### ISSUE THREAD

**Issue by raymclee** [erlangbureau/jamdb_oracle#118]
Hi, Does this library support oracle cloud database?

**Comment by vstavskyi** [comment]
It works with databases in Amazon RDS.

**Comment by vstavskyi** [comment]
See [reply](https://github.com/erlangbureau/jamdb_oracle/issues/98#issuecomment-869162888)

With PEM certificate (-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----) 
try 
`parameters: [..... , ssl: [cert_pem: '/path/to/ewallet.pem', verify: :verify_none]]
`

With certificate and private key (-----BEGIN PRIVATE KEY-----  ... -----END PRIVATE KEY-----) and password
try
`parameters: [..... , ssl: [certfile: '/path/to/cert.pem', keyfile: '/path/to/key.pem', password: 'PASSWORD', verify: :verify_none]]
`

But first, you had to patch erlang ssl application and replace beam file.
