### ISSUE TITLE
Oracle connection error codes

### ISSUE THREAD

**Issue by paulsullivanjr** [erlangbureau/jamdb_oracle#12]
First thank you for creating this. I'm currently setting it up in a phoenix app and was wondering if it was possible to return the oracle connection error code?

**Comment by vstavskyi** [comment]
I understand that client wants to know error details, but it might affect your server. I like [this post](https://tkowal.wordpress.com/2014/09/09/erlang-otp-gen_server-boilerplate/) about Let it crash.

**Comment by paulsullivanjr** [comment]
Thanks for the feedback I'll read the article today. Your point makes sense. I did s but me re debugging and I'm getting a connection but it looks like oracle is responding with a TNS_REDIRECT so jamdb disconnects and tries to reconnect but can't. I'm going to dig into it life and see what's going on with the server. Thanks again.

**Comment by vstavskyi** [comment]
Could you pls paste here dump of request and response packets in pcap or raw. I'll try fix it.

**Comment by paulsullivanjr** [comment]
Sorry for the delay in answering. I was able to get the connection to work.

**Comment by paulsullivanjr** [comment]
Sorry for the delay in answering. I was able to get the connection to work.

**Comment by paulsullivanjr** [comment]
Thanks again for your time.
