### ISSUE TITLE
Translate error codes

### ISSUE THREAD

**Issue by isaacsanders** [erlangbureau/jamdb_oracle#125]
It would be better to process the error code on https://github.com/erlangbureau/jamdb_oracle/blob/master/lib/jamdb_oracle.ex#L50 using some form of the list at http://www.dba-oracle.com/t_error_code_list.htm or some other place that included better error codes.

**Comment by isaacsanders** [comment]
```
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) []
        (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:820: Ecto.Adapters.SQL.execute/6
        (ecto 3.9.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
        (ecto 3.9.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

Without the translation, I would get an error like this.

**Comment by vstavskyi** [comment]
Please try stage branch
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/0fa3e401e6abf97f8a80c309827b8f77db92f1ec)
