### ISSUE TITLE
Retired package: Release invalid - at you own risk

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#128]
@vstavskyi 

I am seeing this while pulling this package. Is this something being worked on?

"Retired package: Release invalid - at you own risk"

We are relying on this package a lot to connect with Oracle and wondering what is happening with this message. Appreciate if you could help clarify.

**Comment by vstavskyi** [comment]
#119
If you don't use large CLOB, just downgrade to 0.5.1

**Comment by vasumur** [comment]
Ok, we are not using CLOBs in our projects. In that case we are safe to be in 0.5.2?

Let us know when there is a fix to #119 will upgrade.

Thanks for the quick response.

**Comment by vstavskyi** [comment]
No, it's unsafe.

https://github.com/erlangbureau/jamdb_oracle/blob/master/test/jamdb_oracle_SUITE.erl#L133
Test FAILED

```
  Ecto.Adapters.SQL.query(YourApp.Repo, "select to_date(:1,:2) to_date from dual where 1=:3", 
   ["'2022-08-01 01:02:03'","'YYYY-MM-DD HH24:MI:SS'",1])

```

0.5.2 - empty result
select to_date(:1,:2) to_date from dual where 1=:3 ["'2022-08-01 01:02:03'", "'YYYY-MM-DD HH24:MI:SS'", 1]        
{:ok, %{columns: ["TO_DATE"], num_rows: 0, rows: []}}

0.5.1 - all ok
select to_date(:1,:2) to_date from dual where 1=:3 ["'2022-08-01 01:02:03'", "'YYYY-MM-DD HH24:MI:SS'", 1]        
{:ok, %{columns: ["TO_DATE"], num_rows: 1, rows: [[~N[2022-08-01 01:02:03]]]}}

**Comment by vasumur** [comment]
@vstavskyi 
I see a new version is out and the issue must have been resolved.

We can close the ticket, if so.

Thanks
