### ISSUE TITLE
crypto:rand_bytes -> crypto:strong_rand_bytes 

### ISSUE THREAD

**Issue by pavelw007** [erlangbureau/jamdb_oracle#13]
Hi, 

I tried to compile your jamdb_oracle erlang driver ( which very pleased me, because I was looking for it for a long time) but it ended with this error :-( 

  jamdb_oracle git:(master) ✗ make app
 ERLC   jamdb_oracle.erl jamdb_oracle_conn.erl jamdb_oracle_crypt.erl jamdb_oracle_tns_decoder.erl jamdb_oracle_tns_encoder.erl
compile: warnings being treated as errors
src/jamdb_oracle_crypt.erl:25: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

Is there any reason why there is still crypto:rand_bytes instaead of crypto:strong_rand_bytes ? 
I have modified jamdb_oracle_crypt.erl ( line 25 ) and it compiled without error, but I'm not sure about the reason crypto:rand_bytes is still in source code ? 

Regards,

Pavel

PS: Thx, for your work.

**Comment by pavelw007** [comment]
Hi again :-), 


after compiling loading and triyng connect, I got this error :-(


12> {ok, Pid} = jamdb_oracle:start_link(Opts).
** exception exit: undef
     in function  jose_jwa_aes:block_decrypt/4
        called as jose_jwa_aes:block_decrypt({aes_cbc,128},
                                             <<170,150,186,146,6,252,239,180,0,0,0,0,0,0,0,0>>,
                                             <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>,
                                             <<40,143,179,25,206,51,43,20,137,139,154,190,173,82,78,
                                               146,173,152,14,224,77,222,163,2,196,...>>)
     in call from jamdb_oracle_crypt:o5logon/4 (src/jamdb_oracle_crypt.erl, line 24)
     in call from jamdb_oracle_tns_encoder:encode_record/4 (src/jamdb_oracle_tns_encoder.erl, line 31)
     in call from jamdb_oracle_conn:send_req/4 (src/jamdb_oracle_conn.erl, line 165)
     in call from jamdb_oracle_conn:handle_login_resp/2 (src/jamdb_oracle_conn.erl, line 114)
     in call from jamdb_oracle:init/1 (src/jamdb_oracle.erl, line 37)
     in call from gen_server:init_it/6 (gen_server.erl, line 328)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 247)
13>

Could there be some consequences with changes I made in source code ? ( crypto:strong_rand_byetes ) 

Thx, 

Pavel

**Comment by vstavskyi** [comment]
Hi, I think it's just missing deps.
Try put jose in deps directory, compile jose, and then start erl program with flag -pa 
`erl -pa ebin deps/*/ebin`
I see compile: warnings too, but compilation ends successfully. Maybe I'll replace rand_bytes in next version.

**Comment by vstavskyi** [comment]
fixed
