### ISSUE TITLE
ConnectionError: Can this be provided a string?

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#138]
Hi @vstavskyi 

Appreciate your help with previous issues. When I am running into a query the below error message is thrown from the driver.

Wondering if this can be provided as a string so we can make use of that?

Thanks... Muralee

{:error, %DBConnection.ConnectionError{message: "<<0, 12, 54, 49, 55, 45, 51, 49, 48, 45, 51, 54, 53, 49, 21, 1, 11, 123, 31, 7, 4, 195, 16, 59, 16, 4, 84, 111, 100, 100, 6, 86, 97, 110, 100, 97, 109, 24, 84, 86, 97, 110, 100, 97, 109, 64, 108, 111, 111, 109, ...>>", severity: :error, reason: :error}}

**Comment by vstavskyi** [comment]
Only this part is as a string
binary_to_list(<<54, 49, 55, 45, 51, 49, 48, 45, 51, 54, 53, 49>> = "617-310-3651" 

Please specify types of  columns and parameters in your query.
like this
select a,b,c from d where e = :1  and f = :2 and g = :3
a - clob
b - string
c - number
:1  - long
:2 - string
:3 - number
