### ISSUE TITLE
Oracle number(8, 2) and the value default 0, Ecto float parse error

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#14]
schema:
  @primary_key false
  schema "members" do
    field :userid, :integer, primary_key: true
    field :useremail, :string
    field :userpassword, :string
    field :userregistereddate, Ecto.Date
    field :user90dvalue, :float

Error bellow when query:

** (ArgumentError) cannot load `0` as type :float for :user90dvalue in schema HelloPhoenix.Member
and the Date type
** (ArgumentError) cannot load `{{2017, 2, 7}, {16, 18, 31}}` as type Ecto.Date for :update_date in schema HelloPhoenix.Member

Any help?

**Comment by vstavskyi** [comment]
try :decimal and :naive_datetime instead

**Comment by yukilau99** [comment]
(ArgumentError) cannot load `0` as type :decimal ,
naive_datetime could fix the date.
but limit met a error:

Repo.all(from( m in Member, select: m, where: m.firstname==^"John", limit: 1))
ORA-00933: SQL command not properly ended

[debug] QUERY ERROR source="members" db=3.5ms
SELECT m0.userid, m0.useremail, m0.userpassword, m0.firstname, m0.lastname, m0.usersalt, m0.usernote, m0.userregistereddate, m0.userstatus, m0.registertype, m0.create_by, m0.userguid, m0.maid, m0.update_by, m0.shippingaddressid, m0.billingaddressid, m0.ebayid, m0.paybycheck, m0.allowcodamount, m0.mandatory, m0.delflag, m0.canreserve, m0.cansfpl, m0.faddtolo, m0.isreseller, m0.discountamount, m0.usergrouptype, m0.tiptimeforprint, m0.allowsfplamount, m0.allowsfpldays, m0.allowcodunsecured FROM members m0 WHERE (m0.firstname = :1) FETCH NEXT 1 ROWS ONLY ["John"]
** (DBConnection.ConnectionError) %{code: 933, message: 'ORA-00933: SQL command not properly ended\n'}
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:113: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
            (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
            (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
            (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
            (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4

**Comment by vstavskyi** [comment]
variable must follow ^ or not?

**Comment by yukilau99** [comment]
should, but I think is the problem of limit,
Repo.all(from( m in Member, select: m, order_by: [asc: m.userid], limit: 1))
ORA-00933: SQL command not properly ended

[debug] QUERY ERROR source="members" db=3.5ms
SELECT m0.userid, m0.useremail, m0.userpassword, m0.firstname, m0.lastname, m0.usersalt, m0.usernote, m0.userregistereddate, m0.userstatus, m0.registertype, m0.create_by, m0.userguid, m0.maid, m0.update_by, m0.shippingaddressid, m0.billingaddressid, m0.ebayid, m0.paybycheck, m0.allowcodamount, m0.mandatory, m0.delflag, m0.canreserve, m0.cansfpl, m0.faddtolo, m0.isreseller, m0.discountamount, m0.usergrouptype, m0.tiptimeforprint, m0.allowsfplamount, m0.allowsfpldays, m0.allowcodunsecured FROM members m0 ORDER BY m0.userid FETCH NEXT 1 ROWS ONLY []
** (DBConnection.ConnectionError) %{code: 933, message: 'ORA-00933: SQL command not properly ended\n'}
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:113: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
            (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
            (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
            (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
            (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Quer

I run the sql
SELECT * FROM members m0 WHERE m0.userid>0 ORDER BY m0.userid FETCH FIRST 1 ROWS ONLY;
 in DBeaver, will popup this error:
SQL Error [933] [42000]: ORA-00933: SQL command not properly ended
  java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

**Comment by vstavskyi** [comment]
seems fetch clause is 12c feature only

**Comment by yukilau99** [comment]
Sorry, the :decimal still meet this error. Number(8, 2)
(ArgumentError) cannot load '0' as type :decimal ,

**Comment by vstavskyi** [comment]
I catch this error too.
Please specify elixir types which you are currently using or planning to use.

**Comment by yukilau99** [comment]
:float I plan to use. when the value is “0.0”, it works, but when “0”, seems it treat it as an integer and cannot parse as a float. I think “0”should be a float. how to fix it?

**Comment by vstavskyi** [comment]
Now driver returns :integer if column scale is 0
So, modify column ID to NUMBER(*,0)
If column type NUMBER, FLOAT, BINARY_DOUBLE, BINARY_FLOAT and scale is not 0 or default then driver returns :float

**Comment by vstavskyi** [comment]
try Ecto.DateTime instead Ecto.Date

**Comment by yukilau99** [comment]
In my Oracle the column is Number(9, 2), the value could store 99.99 or 0 by design, 
when the value is 0,  the value return from sql is "0", not "0.0"
I think driver treat this "0" as Integer, 
whatever I use :float or :decimal in model schema, error still occurred.

**Comment by vstavskyi** [comment]
There is issue with SUM and MAX functions, because Oracle returns scale 0 for both  integer and float  SUM and MAX values, but column select must work with this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/8300178a2823a73512d4925be134f90171da07c9).
Please check that you'are using all new .ex .erl and  .hrl

**Comment by vstavskyi** [comment]
Or, if id column is number(8, 2), describe it in schema like this: @primary_key {:id, :float, autogenerate: false}

**Comment by yukilau99** [comment]
Thank you, did you publish to hex.pm?

**Comment by vstavskyi** [comment]
published

**Comment by yukilau99** [comment]
Cool! test passed, thank you very much!
