### ISSUE TITLE
First line comment in the SQL statement fails the query.

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#142]
As you see below if the first line is a comment then the query is not returning any results, but as soon as remove the first line commend it works

```
iex(15)> query
"-- first line comment\nselect 'x' as dummy from dual\n"

iex(16)> Ecto.Adapters.SQL.query(MyRepo, query, [],[])
{:ok, %{rows: [[]], num_rows: 1}}

iex(17)> query1
"\nselect 'x' as dummy from dual\n"

iex(18)> Ecto.Adapters.SQL.query(SMyRepo, query1, [],[])
{:ok, %{columns: ["DUMMY"], rows: [["x"]], num_rows: 1}}

```

**Comment by vstavskyi** [comment]
just move comment to the end

**Comment by vstavskyi** [comment]
try new function strip 
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/40d5f454b71d179ac4b6c1cd9a8f46c8e537ae23)

`sql = Jamdb.Oracle.strip(sql)`

**Comment by vasumur** [comment]
Was wondering if this can be done prior to the execution in the library?

This should help with any logging sql without stripping comments etc that rely on those comments for readability etc.
