### ISSUE TITLE
schema_migrations table not created?

### ISSUE THREAD

**Issue by mlooney** [erlangbureau/jamdb_oracle#143]
The migration process seem to not create the schema_migrations table, despite  jamb_oracle_query.ex generating the DDL on line 591.  This causes migrations to fail later, for the lack of said table.

(jamdb_oracle 0.5.5, ecto_sql 3.6)

**Comment by vstavskyi** [comment]
CREATE TABLE schema_migrations (version bigint, ....    
failed because of bigint
fixed on L821
