### ISSUE TITLE
Expressions in select maps not understood by Oracle 19c

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#147]
Running a query like this

```elixir
from f in "foo",
  select: %{
    res: f.a == 1
  }
```

gets translated into SQL like

```SQL
SELECT (a = 1) as res FROM foo
```

which at least my *Oracle 19c* does not support.
(`ORA-00907: missing right parenthesis`)

A minor issue, as it can be worked around in this case with a fragment and a 'CAST' expression, but this works with the Postgresql Ecto adapter for example.

Greetings, David

**Comment by vstavskyi** [comment]
What the result of `f.a == 1`? 
Boolean?

**Comment by dfrese** [comment]
In Postgres? Yes.

Something like
```elixir
select: %{
  res: f.myint + 5
}
```
works, btw.

**Comment by vstavskyi** [comment]
In Oracle boolean is rare

**Comment by vstavskyi** [comment]
In 23c
```
select  dump(1=2), dump(1=1), 1=1  from dual []
{:ok,
 %{
   columns: ["DUMP(1=2)", "DUMP(1=1)", "1=1"],
   num_rows: 1,
   rows: [["Typ=252 Len=1: 0", "Typ=252 Len=1: 1", 1]]
 }}
```
