### ISSUE TITLE
Error loading rows that used the :identity primary key type in create table migration

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#148]
Hi!

I used the `:identity` primary key type to create a table via ecto.migrate. That uses `number` as the column type as defined in:

```elixir
  defp ecto_to_db(:identity),            do: "number generated by default as identity"
```

But after inserting a row like that, there is a problem reading that via Ecto.Repo. The error is raised at `Ecto.Repo.Queryable.struct_load!/6`:

```
cannot load `1.0` as type :id for field :id in %MySchema...
```

Seems the is is somehow read as a floating point number.
The schema `MySchema` was defined with

```elixir
      @primary_key {:id, :id, autogenerate: true}
```

When I use `:"number(38,0) generated by default as identity"` as the primary key column type, it all works fine!

**Comment by vstavskyi** [comment]
`integer generated by default as identity` 
Looks better

**Comment by vstavskyi** [comment]
[fixed](https://github.com/erlangbureau/jamdb_oracle/commit/4dd14be0c115349604c7c1f635cb9e50142050a0)
