### ISSUE TITLE
ORA-01086: savepoint \'TRAN\' never established in this session or is invalid

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#149]
When a Ecto.Repo.transaction fails, I often see the above error in the **logs** (with Oracle 19c)

I changed the start/abort transaction statements in `jamdb_oracle.ex` from

```elixir
        statement = "SAVEPOINT tran"
...
        statement = "ROLLBACK TO tran"
```
to 
```elixir
        statement = "SET TRANSACTION READ WRITE"
...
        statement = "ROLLBACK"
```

I don't know enough about Oracle to say if this is equivalent, or 'better', but at least it prevented the above error in the logs.
(I only see the actual error that caused the transacton to abort as a ConnectionError exception)

**Comment by vstavskyi** [comment]
`ROLLBACK TO SAVEPOINT tran`
Maybe keyword SAVEPOINT helps

**Comment by vstavskyi** [comment]
Check connection parameters
`parameters: [autocommit: 0,...`

**Comment by dfrese** [comment]
Thanks, that prevents the error log too.

But doesn't it affect other statements that are not run in a `Ecto.Repo.transaction`?

**Comment by vstavskyi** [comment]
Use Repo.query("COMOFF") and Repo.query("COMON") when you need

See [jamdb_oracle_conn.erl ](https://github.com/erlangbureau/jamdb_oracle/blob/master/src/jamdb_oracle_conn.erl#L115)
L115-L126
#31
