### ISSUE TITLE
Binary length should be considered in o5logon/4

### ISSUE THREAD

**Issue by muscl** [erlangbureau/jamdb_oracle#15]
Jamdb_oracle works fine in Linux oracle, but not in windows oracle.
Then I found this issue: the length of Rest1 may be less than 32, so the code(with "+") below may be the better choice.

```
-    Rest2 = crypto:block_encrypt(des_cbc, binary:part(Rest1,24,8), IVec, CliPass),
-    Data = binary:part(Rest2,24,8),
+    Rest2 = crypto:block_encrypt(des_cbc, binary:part(Rest1, size(Rest1)-8, 8), IVec, CliPass),
+    Data = binary:part(Rest2, size(Rest2)-8, 8),
```

**Comment by vstavskyi** [comment]
Hi! Did you check the result of CliPass = norm(User++Pass). Maybe User or  Pass too short or contains weird characters?

**Comment by vstavskyi** [comment]
Please try this:
```
58 -N = (8 - (length(S) rem 8 )) rem 8,
58 +N = 16 - (length(S) rem 16),
```

**Comment by vstavskyi** [comment]
fixed
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/1d2866e36754195d6a5888c0f83dd38e11a301f2)
