### ISSUE TITLE
Extracting constraint names

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#155]
Constraints are currently not extracted from Oracle-Errors.

in `jamdb_oracle_query.ex':

```elixir
  def to_constraints(_err, _opts \\ []), do: []
```

So `unique_constraint`, `no_assoc_constraint`, `foreign_key_constraint` and `check_constraint` from `Ecto.Changeset` don't work.

**Comment by vstavskyi** [comment]
Check stage branch

[Create jamdb_oracle_sql.ex](https://github.com/erlangbureau/jamdb_oracle/commit/b0d60dc97a776d5c327d61beb95a0ef2841d6a59) 
[defdelegates](https://github.com/erlangbureau/jamdb_oracle/commit/556e86bb6b02f6b8f6c567d7d7763af9462c9a35)
