### ISSUE TITLE
Error: ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by xsir99** [erlangbureau/jamdb_oracle#16]
I'm a new oracle user, I get lots of errors of `ORA-01000: maximum open cursors exceeded` while query in a loop, and I learn some knowledge about this cursors, it says the cursors should be closed, so I want to kown  , if there is a API  to release the cursors ? Thanks!

**Comment by vstavskyi** [comment]
Hi! Java driver has the same problem. See [this post](https://stackoverflow.com/questions/12192592/java-sql-sqlexception-ora-01000-maximum-open-cursors-exceeded). Like in java driver, I close cursors just before logoff with encode_record(close, Cursors)

**Comment by vstavskyi** [comment]
I'll try to send this packet to server every 100 cursors. Maybe it'll work for them.
```
 <<
    ?TTI_PFN,
    (encode_ub2(?TTI_OCCA))/binary,
    1,
    (encode_sb4(length(Cursors)))/binary,  %cursors count
    (encode_array(Cursors))/binary        %cursors
  >>
```

**Comment by kagux** [comment]
Hey @vstavskyi,

I'm having similar issues. I execute a simple SELECT query multiple times. After about couple thousand queries it runs out of 300 cursors.
I'm using ecto adapter by the way. Is there anything I can do to reduce number of cursors? Do you know why they keep accumulating?

Thanks!

**Comment by vstavskyi** [comment]
I found [this](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:685336504294). 
Closed cursors remains in cache that freed only after the close of the session.

**Comment by kagux** [comment]
I've tested running same select query multiple times using external application (DataGrip) and using this driver. DataGrip creates 1 cursor during whole session, while driver creates 1 cursor per each request.
For now the only workaround is to restart `Repo` to close all sessions before they run out of cursors. But I wonder if cursors can be closed after executing queries.

**Comment by vstavskyi** [comment]
I tried to send modified encode_record(close, Cursors) without ?TTI_LOGOFF, no answer from database.

**Comment by vstavskyi** [comment]
I'll exemine DataGrip packets soon. Maybe I can find something usefull.

**Comment by vstavskyi** [comment]
Please test last ver 0.1.0
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/808268db246c461bfdf80d6b41020170529cc1aa)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/6e0d0c6224c05627378ba8861263dff2fe5917de)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/a10c6b394bd7594aec23317420849edc9f66e6cb)

**Comment by kagux** [comment]
works like a charm, thanks!

**Comment by c-bik** [comment]
I have started get the [same error](https://travis-ci.org/c-bik/ora_bench/builds/590529551#L421) in a bench marking test I wrote [`jamdb_oracle:sql_query`](https://github.com/c-bik/ora_bench/blob/master/test/jamdb_oracle_SUITE.erl#L85).
What am I missing?
TIA
