### ISSUE TITLE
Inconsistency when creating indices with a prefix

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#166]
The 'create index' migration with a `prefix: mike` option emits a statement like

```sql
create index tab_col on mike.tab (col)
```

but dropping it emits

```sql
drop index mike.tab_col
```

And depending on the username that is used in the connection, that actually makes a difference.
This can cause a 'name already used error', as the index is apparently create under the logged in user, ignoring the prefix:

```sql
create index tab_col on mary.tab (col)
create index tab_col on mike.tab (col)   -- fails
```

I suggest to add the prefix like so
```sql
create index mike.tab_col on mike.tab (col)
```

In `jamdb_oracle_sql.ex` that is easily done by

```elixir
quote_name(index.name)

=>

quote_table(index.prefix, index.name)
```
both in `execute_ddl` for  the `Index :create`, and for the `Index :rename` case.

That would make it consistent with `drop index` and also avoid the name clash.

**Comment by vstavskyi** [comment]
Failed without ORA error?

[test](https://github.com/erlangbureau/jamdb_oracle/blob/master/test/jamdb_oracle_test.exs#L1136) "create index with prefix"
[test](https://github.com/erlangbureau/jamdb_oracle/blob/master/test/jamdb_oracle_test.exs#L1191) "drop index with prefix"

**Comment by dfrese** [comment]
Are you sure it's not needed for alter/rename index (and alter/rename table for that matter)?

**Comment by vstavskyi** [comment]
I'm sure about rename 
ORA-01765: specifying owner's name of the table is not allowed
