### ISSUE TITLE
SQL syntax error in insert_all and with_cte

### ISSUE THREAD

**Issue by dfrese** [erlangbureau/jamdb_oracle#168]
An `insert_all` with a query of the data to be inserted, which has a 'CTE', generates an SQL string like

`sql
INSERT INTO foo (WITH bar AS ...)
`

which gives me an Oracle error

`
ORA-32034: unsupported use of WITH clause
`

Removing the braces around the WITH works, which can be achieved by changing the `insert_all` clause in `jamdb_oracle_query.ex` to:

```elixir
   defp insert_all(query = %Ecto.Query{}, _counter) do
     [all(query)]
   end
```

(`cte_query` in line 253 adds braces too, but that didn't seem relevant here)

**Comment by vstavskyi** [comment]
[fix](https://github.com/erlangbureau/jamdb_oracle/commit/09ac7362b2eb2a3b53261908cb77a662ca8f0df9)
