### ISSUE TITLE
Incompatible with Ecto 2.2

### ISSUE THREAD

**Issue by kagux** [erlangbureau/jamdb_oracle#17]
Hey,

Thanks for building this library!

Ecto 2.2 introduced breaking changes to your library.

```
== Compilation error in file lib/jamdb_oracle_query.ex ==
** (CompileError) lib/jamdb_oracle_query.ex:287: unknown key :fields for struct Ecto.SubQuery
    lib/jamdb_oracle_query.ex:287: (module)
```

**Comment by vstavskyi** [comment]
Fast fix [commit](https://github.com/erlangbureau/jamdb_oracle/commit/7efb12f86b93e067933ec6a3e323d23bfd58a430)

**Comment by kagux** [comment]
Thanks @vstavskyi! I've opened exactly the same PR against my fork instead of this repo by accident :)

**Comment by collegeimprovements** [comment]
Is there any example how to use `jamdb_oracle` with  `elixir` and `ecto` ?

**Comment by vstavskyi** [comment]
Just replace Postgre  with Oracle in  [Adding Ecto to an application](https://hexdocs.pm/ecto/getting-started.html#adding-ecto-to-an-application) and [Composing Ecto queries](https://hexdocs.pm/ecto/getting-started.html#composing-ecto-queries). It works the same way.

**Comment by vstavskyi** [comment]
Please test new test/test_helper.exs with 2.2.
Maybe I missed new pool config parameter or something else and got an error:
> ... EXIT ... Ecto.Registry, {:associate, ... no process currently associated with the given name ...
