### ISSUE TITLE
Elixir 1.16.0-otp-26 and erlang 26.0.2 breaking queries with jamdb_oracle 0.5.7 version.

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#170]
In the above mentioned combination if I use jamdb_oracle 0.5.4 version the queries are bringing results without any error.

Only with 0.5.7 version the queries are failing with different errors.

@vstavskyi  Appreciate if you could look into this. Let me know if you need any details

My function to get data looks like below.

```
    case Ecto.Adapters.SQL.query(
           __MODULE__,
           query,
           args,
           opts
         ) do
      {:ok, %{rows: rows}} ->
        rows |> Enum.map(fn row -> Enum.zip(columns, row) |> Enum.into(%{}) end)
      error ->
        Logger.error(
          "Error while executing query = #{inspect(query)} for args = #{inspect(args)}. Error = #{inspect(error)}"
        )
        raise "Error while executing query = #{inspect(query)} for args = #{inspect(args)}. Error = #{inspect(error)}"
    end
```

**Comment by vasumur** [comment]
Appreciate if this could be looked into.

**Comment by vstavskyi** [comment]
I got `undefineded function pubkey_pbe:pbdkdf2` error with elixir 1.15 on both 0.5.4 and 0.5.7
try master branch 0.5.8
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/f900f52f96c11284840c8c11dc495110d068be68)

**Comment by vasumur** [comment]
Do you have a schedule when this will be available in hex?

```
Because your app depends on jamdb_oracle 0.5.8 which doesn't match any versions, version solving failed.
```

**Comment by vstavskyi** [comment]
February 6

**Comment by vstavskyi** [comment]
Declare :crypto and :public_key extra applications in mix.exs
```
  def application do
    [
      extra_applications: [:crypto, :public_key]
    ]
  end
```
