### ISSUE TITLE
Connecting in Oracle 11g.

### ISSUE THREAD

**Issue by braulio** [erlangbureau/jamdb_oracle#18]
Hello! I trying to connect in Oracle 11g. Using iex -S mix, apparently it connects but soon afterwards I get this error message:

[error] Jamdb.Oracle (#PID <0.380.0>) failed to connect: ** (ErlangError) Erlang error: {{: badmatch, {: error,: socket,: timeout, {: oraclient, #Port <0.14572 >,: disconnected, 1,: select, 15000, '458CE7535768DF1423FE86A2F335BA81', 15,: undefined, [], [], [timeout: 15000, password: '***', user: '**', port: 1521 , host: '10 .0.2.117 ', service_name:' *** ']}}}, [{: jamdb_oracle,: init, 1, [file:' src / jamdb_oracle.erl ', line: 37]}, {: init_it, 6, [file: 'gen_server.erl', line: 333]}, {: proc_lib, init_it, : init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}

What can be happening ??

Thank you.

**Comment by vstavskyi** [comment]
Hello!  Try to change **timeout** parameter to 30000 or infinity. But first, supply connection details for your database in test/jamdb_oracle_test.exs and run **mix test**.

**Comment by braulio** [comment]
Run in Oracle RAC??
