### ISSUE TITLE
Authentication fails on some Oracle Database 19c nodes

### ISSUE THREAD

**Issue by yastanotheruser** [erlangbureau/jamdb_oracle#183]
Bisecting from master to 287f584d, I found authentication works by reverting 305c989d. The authentication attempt fails silently in my Elixir app, but using the Erlang modules it looks like the socket closes the connection.

**Comment by vstavskyi** [comment]
Please try master. 
Redirect should work now.

**Comment by yastanotheruser** [comment]
It's working now, thank you!
