### ISSUE TITLE
`:fetch` parameter raises 'ORA-01002: fetch out of sequence'

### ISSUE THREAD

**Issue by kagux** [erlangbureau/jamdb_oracle#19]
Hey,

I've tried using `:fetch` parameter, but query returns an error:

```
11:53:36.011 [debug] QUERY ERROR source="cptra_functional_groups" db=417.0ms
SELECT c0.fn_group_id, c0.short_name FROM cptra_functional_groups c0 []

11:53:36.024 [error] #PID<0.452.0> running Milo.Web terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) %{code: 1002, message: 'ORA-01002: fetch out of sequence\n'}
        (jamdb_oracle) lib/jamdb_oracle_ecto.ex:141: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
        (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
        (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
        (milo) lib/milo/category.ex:16: anonymous fn/1 in Milo.Category.get_short_names_indexed_by_id/0
        (cachex) lib/cachex/util.ex:77: Cachex.Util.get_fallback/4
        (cachex) lib/cachex/actions/get.ex:42: Cachex.Actions.Get.handle_record/4
```

**Comment by vstavskyi** [comment]
:fetch parameter is similar to the Oracle JDBC driver's **defaultRowPrefetch** parameter that improves performance by reducing round trips to the database.
For example, if query returns 100 rows and overall size is less 1500 (Ethernet frame), we can improve application and network performance by setting :fetch over 100.
With default value of 15 it will be 7 send packets and 7 recv packets.
When row size is about 8Kb or more, I tested different values: 1, 2 and sometimes got errors too.

**Comment by kagux** [comment]
@vstavskyi, our select query returns a lot of rows, I was hoping to reduce number of fetches just like you described. Do you know what causes the error?

**Comment by vstavskyi** [comment]
I found this:
> This [ORA-01002] can occur if an attempt was made to FETCH from an active set after all records have been fetched.

This should refer to cursor, but not to select.
Did you test your statement in java?

**Comment by kagux** [comment]
I'm using ecto adapter to execute simple select like so: `MyApp.Repo.all User`
I haven't tested anything in java. To be honest, I have no idea how to and what's the statement produced by oracle driver.

**Comment by vstavskyi** [comment]
You can add  IO.inspect in jamdb_oracle.ex:
```
def query(s, sql, params \\ []) do
+ IO.inspect sql
```
Or add io:format in jamdb_oracle.erl:
```
sql_query(Pid, Query) ->
+ io:format("~p~n", [Query]),
```

**Comment by kagux** [comment]
An update to this issue:
* out of sequence error is caused by `autocommit` option, not `fetch`
* `fetch` on the other hand works for some values (I tried 10, 20, 30, 40), but causes errors in decoder for higher values (50, 100, 1000).
