### ISSUE TITLE
oracle login error

### ISSUE THREAD

**Issue by chenyu468** [erlangbureau/jamdb_oracle#2]
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|recv|292|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_290:
        <<>>
        <<0,11,0,0,12,0,0,0,1,0,1>>
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|recv|285|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_283:
        <<>>
2016-03-22 22:32:10.931 [debug] |jamdb_oracle|jamdb_oracle_conn|handle_login_resp|161|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|_161:
        12
        <<1,0,1>>
2016-03-22 22:32:10.932 [error] |Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|Undefined|CRASH REPORT Process <0.76.0> with 0 neighbours exited with reason: no match of right hand value login_failed in jamdb_oracle:init/1 line 37 in gen_server:init_it/6 line 330
*\* exception error: no match of right hand side value {error,{{badmatch,login_failed},
                                                              [{jamdb_oracle,init,1,
                                                                             [{file,"src/jamdb_oracle.erl"},{line,37}]},
                                                               {gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},
                                                               {proc_lib,init_p_do_apply,3,
                                                                         [{file,"proc_lib.erl"},{line,237}]}]}}

**Comment by kostyushkin** [comment]
> login_failed

Current implementation expects that you specify the correct options for a connection

**Comment by chenyu468** [comment]
Opts = [
    {host, "xxx.auto-library.cn"},
    {port, 1521},
    {user, "chenyu"},
    {password, "chenyu"},
    {sid, "orcl"},
    {app_name, "OFFICE"}
].
{ok, Pid} = jamdb_oracle:start_link(Opts).

**Comment by newsdy** [comment]
tnsname.ora: 
`ORCL =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = orcl)
    )
  )`

What is sid, app_name ? how to connect it? i know host, user, passwd, port.
I met the same problem
@chenyu468 @kostyushkin 
thx

**Comment by kostyushkin** [comment]
SID and SERVICE_NAME is the same, see https://docs.oracle.com/cd/B28359_01/network.111/b28317/tnsnames.htm#i47792
At the moment I don't have a server for testing, so i can't investigate this issue. If you can give me one with the same configuration, I can fix this problem

**Comment by own-star** [comment]
=CRASH REPORT==== 11-Jan-2017::08:17:05 ===
  crasher:
    initial call: jamdb_oracle:init/1
    pid: <0.3502.0>
    registered_name: []
    exception exit: {undef,
                        [{jose_jwa_aes,block_decrypt,
                             [{aes_cbc,128},
                              <<40,48,27,26,122,126,134,238,0,0,0,0,0,0,0,0>>,
                              <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>,
                              <<205,232,151,14,55,195,132,185,153,47,14,147,
                                49,219,192,159,48,114,72,184,102,198,165,243,
                                71,85,135,230,124,34,143,191>>],
                             []},
                         {jamdb_oracle_crypt,o5logon,4,
                             [{file,"src/jamdb_oracle_crypt.erl"},{line,24}]},
                         {jamdb_oracle_tns_encoder,encode_record,4,
                             [{file,"src/jamdb_oracle_tns_encoder.erl"},
                              {line,29}]},
                         {jamdb_oracle_conn,send_req,4,
                             [{file,"src/jamdb_oracle_conn.erl"},{line,155}]},
                         {jamdb_oracle_conn,handle_login_resp,2,
                             [{file,"src/jamdb_oracle_conn.erl"},{line,109}]},
                         {jamdb_oracle,init,1,
                             [{file,"src/jamdb_oracle.erl"},{line,37}]},
                         {gen_server,init_it,6,
                             [{file,"gen_server.erl"},{line,328}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:init_it/6 (gen_server.erl, line 352)
    ancestors: [<0.3500.0>,<0.3372.0>,<0.3371.0>,ranch_sup,<0.3358.0>]
    messages: []
    links: [#Port<0.2674>,<0.3500.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2431
  neighbours:

jose has function jose_jwa_aes:block_decrypt/4, why it's undefined?

**Comment by own-star** [comment]
I added 
{included_applications, [
  jose
]},

to jamdb_oracle.app.src for fixing

**Comment by vstavskyi** [comment]
>how to connect with SERVICE_NAME
fixed
Opts = [
{host, "127.0.0.1"},
{port, 1521},
{user, "test"},
{password, "test"},
%%{sid, "orcl"},
{service_name, "orcl"},
{app_name, "orcl"}
].
>I added {included_applications, [jose]}, to jamdb_oracle.app.src for fixing
fixed
