### ISSUE TITLE
Set connection encoding

### ISSUE THREAD

**Issue by AxelRHD** [erlangbureau/jamdb_oracle#24]
I have an OracleDB with a very bad encoding (I can't change). In Ruby I can set a paramter in the driver (`OCI8.encoding = 'Windows-1252'`). Would be great if this worked for the Elixir-driver too.

**Comment by vstavskyi** [comment]
Now result is utf8 encoded. Are any characters converted to a replacement character?

**Comment by AxelRHD** [comment]
Thank you. I will give it a try tomorrow at the office. What do you mean with the conversion of replacement characters? We have the german characters "äöüß" which cause these problems.

**Comment by vstavskyi** [comment]
I refer to [this](https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch2charset.htm#i1006853) guide.

> For example, ä (a with an umlaut) may be converted to a.
