### ISSUE TITLE
 (ArgumentError) cannot load `8634.0` as type :integer for field

### ISSUE THREAD

**Issue by bossyang** [erlangbureau/jamdb_oracle#25]
Oracle EBS usually uses `NUMBER` as primary key or integer column, not `NUMBER(n, 0)`. Changing type to `:decimal` doesn't work, either.

```elixir
defmodule Todos.EBS.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias Todos.EBS.Item

  @primary_key {:inventory_item_id, :integer, []}
  @derive {Phoenix.Param, key: :inventory_item_id}
  schema "mtl_system_items_b" do
    field :segment1
    field :description
    field :organization_id, :integer
  end
end
```

```
iex(2)> OracleRepo.get!(Item, 8634)
[debug] QUERY ERROR source="mtl_system_items_b" db=4.3ms decode=0.1ms
SELECT m0.inventory_item_id, m0.segment1, m0.description, m0.organization_id FROM mtl_system_items_b m0 WHERE (m0.inventory_item_id = :1) [8634]
** (ArgumentError) cannot load `8634.0` as type :integer for field `inventory_item_id` in schema Todos.EBS.Item
    (ecto) lib/ecto/schema.ex:1493: Ecto.Schema.load!/5
    (ecto) lib/ecto/schema.ex:1441: Ecto.Schema.safe_load_zip/4
    (ecto) lib/ecto/schema.ex:1429: Ecto.Schema.__safe_load__/6
    (ecto) lib/ecto/repo/queryable.ex:275: Ecto.Repo.Queryable.process_source/6
    (ecto) lib/ecto/repo/queryable.ex:170: Ecto.Repo.Queryable.preprocess/5
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (jamdb_oracle) lib/jamdb_oracle.ex:189: DBConnection.Query.Jamdb.Oracle.Query.decode/3
    (db_connection) lib/db_connection.ex:1011: DBConnection.decode/6
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:118: Ecto.Adapters.Jamdb.Oracle.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:78: Ecto.Repo.Queryable.one!/4
```

Table MTL_SYSTEM_ITEMS_B DDL
```sql
CREATE TABLE MTL_SYSTEM_ITEMS_B (
	INVENTORY_ITEM_ID NUMBER,
	ORGANIZATION_ID NUMBER,
	LAST_UPDATE_DATE DATE,
	LAST_UPDATED_BY NUMBER,
	CREATION_DATE DATE,
	CREATED_BY NUMBER,
	LAST_UPDATE_LOGIN NUMBER,
	SUMMARY_FLAG VARCHAR2(1),
	ENABLED_FLAG VARCHAR2(1),
	START_DATE_ACTIVE DATE,
	END_DATE_ACTIVE DATE,
	DESCRIPTION VARCHAR2(240),
	BUYER_ID NUMBER(9,0),
	ACCOUNTING_RULE_ID NUMBER,
	INVOICING_RULE_ID NUMBER,
	SEGMENT1 VARCHAR2(40),
```

**Comment by bossyang** [comment]
It can work with float type. But it doesn't make sense, right?
```
iex(4)> query2 = from c in Item, where: c.segment1 == "6101" and c.organization_id == ^83
#Ecto.Query<from i in Todos.EBS.Item,
 where: i.segment1 == "6101" and i.organization_id == ^83>
iex(6)> OracleRepo.all query2
[debug] QUERY OK source="mtl_system_items_b" db=4.6ms
SELECT m0.inventory_item_id, m0.segment1, m0.description, m0.organization_id FROM mtl_system_items_b m0 WHERE ((m0.segment1 = '6101') AND (m0.organization_id = :1)) [83.0]
[%Todos.EBS.Item{__meta__: #Ecto.Schema.Metadata<:loaded, "mtl_system_items_b">,
  description: "24H賦活液", inventory_item_id: 8889.0, organization_id: 83.0,
  segment1: "6101"}]
```

```elixir
defmodule Todos.EBS.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias Todos.EBS.Item

  @primary_key {:inventory_item_id, :float, []}
  @derive {Phoenix.Param, key: :inventory_item_id}
  schema "mtl_system_items_b" do
    field :segment1
    field :description
    field :organization_id, :float
  end
end
```

**Comment by vstavskyi** [comment]
In terms of Oracle:
INTEGER  - A whole number
NUMBER  - A decimal (float) number;  A whole number if scale is 0
So, if ID is a whole number, type must be INTEGER or NUMBER(n,0), 
otherwise ID is a decimal (float) number.

**Comment by vstavskyi** [comment]
Ecto 2.1 raises error when :id is 1.0 or when :float is 1.
Is there any changes in 2.2?

**Comment by bossyang** [comment]
I use Oracle Database 11g. I think there is no data type `INTEGER` actually. So Oracle EBS always uses `NUMBER` as table primary key. And its value is a whole number.
 
https://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements001.htm#SQLRF0021

> Specify an integer using the following form:
> 
> `NUMBER(p)`
> This represents a fixed-point number with precision p and scale 0 and is equivalent to NUMBER(p,0).

https://ss64.com/ora/syntax-datatypes.html

> INTEGER
> This ANSI datatype will be accepted by Oracle - it is actually a synonym for NUMBER(38)

> The NUMBER datatype 
> Stores zero, positive, and negative numbers, fixed or floating-point numbers
> **Integer NUMBER**
> `NUMBER(p)`
> This is a fixed-point number with precision p and scale 0. Equivalent to NUMBER(p,0)

**Comment by bossyang** [comment]
Check the eTRM http://etrm.oracle.com/pls/etrm/etrm_pnav.show_object?c_name=MTL_SYSTEM_ITEMS_B&c_owner=INV&c_type=TABLE

> The primary key for an item is the INVENTORY_ITEM_ID and ORGANIZATION_ID. 

Name | Datatype | Length | Mandatory | Comments
-- | -- | -- | -- | --
INVENTORY_ITEM_ID | NUMBER |   | Yes | Inventory item identifier
ORGANIZATION_ID | NUMBER |   | Yes | Organization identifier
LAST_UPDATE_DATE | DATE |   | Yes | Standard Who column
LAST_UPDATED_BY | NUMBER |   | Yes | Standard Who column
CREATION_DATE | DATE |   | Yes | Standard Who column
CREATED_BY | NUMBER |   | Yes | Standard Who column
LAST_UPDATE_LOGIN | NUMBER |   |   | Standard Who column
SUMMARY_FLAG | VARCHAR2 | (1) | Yes | Flexfield summary flag
ENABLED_FLAG | VARCHAR2 | (1) | Yes | Flexfield segment enabled flag
START_DATE_ACTIVE | DATE |   |   | Flexfield segment start date
END_DATE_ACTIVE | DATE |   |   | Flexfield segment end date
DESCRIPTION | VARCHAR2 | (240) |   | Item description is maintained in the installation base language only. Translations table (MTL_SYSTEM_ITEMS_TL) holds item descriptions in multiple languages
BUYER_ID | NUMBER | (9) |   | Buyer identifier
ACCOUNTING_RULE_ID | NUMBER |   |   | Accounting rule identifier
INVOICING_RULE_ID | NUMBER |   |   | Invoicing rule identifier

**Comment by vstavskyi** [comment]
Many case and guard expressions of Ecto, for example in ecto\query\builder.ex, are strict :        
```
is_float(n)   -> :float  
is_integer(n) -> :integer
```
That expressions must be less strict, because we know that 1 == 1.0 .
And that's why we must declare primary keys as :float.

**Comment by bossyang** [comment]
I think I need a custom Ecto Type to deal with the legacy database schema. Or I have to convert the `XYZ_ID` column from float to interger every time, right?

**Comment by vstavskyi** [comment]
Just declare  @primary_key as :float like you already did
` @primary_key {:inventory_item_id, :float, []}`

**Comment by bossyang** [comment]
Check the example in my 2nd comment. Since we declare these ID fields as float type, the return values are all float number. Instead EBS stores value inventory_item_id as 8889 and organization_id as 83.

**Comment by vstavskyi** [comment]
Then You need a custom Ecto Type.

**Comment by bossyang** [comment]
@vstavskyi Thank you for your patience and the awesome package!
