### ISSUE TITLE
ecto migration failed

### ISSUE THREAD

**Issue by bossyang** [erlangbureau/jamdb_oracle#26]
Not support yet?
```
** (MatchError) no match of right hand side value: {:error, {Jamdb.Oracle, {'no such file or directory', 'Elixir.Jamdb.Oracle.app'}}}
    (ecto) lib/mix/ecto.ex:99: Mix.Ecto.ensure_started/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:76: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

```elixir
config :my_ebs, MyEbs.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  username: "oracle",
  password: "password",
  database: "TEST",
  hostname: "10.40.10.16",
  pool_size: 2,
  port: 1521
```

```elixir
defmodule MyEbs.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users) do
      add :username, :string
      add :password, :string
      timestamps()
    end
  end
end
```

**Comment by vstavskyi** [comment]
Not yet. 
Migration begins with DROP DATABASE and any Oracle DBA would've refused.
I think migration is only for postgre or mysql.

**Comment by bossyang** [comment]
Got it.

**Comment by capitalist** [comment]
fwiw, migrate will take a `-r` flag. So if you have multiple repos, and oracle is one of them you can `mix ecto.migrate -r SomeApp.NotOracleRepo`

**Comment by garthk** [comment]
I think the issue this duplicates is #11, no?

@vstavskyi please reconsider: even if an Oracle DBA will refuse to let `ecto.reset` DROP DATABASE or `ecto.migrate` add to or modify table schemata _in production_, not being able to do either _in development_ is an obstacle to adoption. 

Take Oracle Cloud as an example: the free tier includes an Oracle database. I want to demonstrate Elixir on it, but I've never used Oracle before. It might well have been easy if I could `ecto.migrate`, but instead I'll either have to learn a lot about Oracle administration or migration, or deploy PostgreSQL or MySQL on my hosts, and right now the latter looks like a quicker way to get back to my Elixir code.

I'm happy to help such an effort once it's going, but getting started would need your or similar expertise.
