### ISSUE TITLE
How to insert the ID of record from Sequence nexval?

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#28]
I can use Ecto.Adapters.SQL.query(Repo, "SELECT SEQ_1.nextval FROM dual",[]) to get the ID, but is there other graceful way to do this?
Thanks.

**Comment by vstavskyi** [comment]
Ugly way: 
```
create function get_nextval (l_seqname varchar2)
return number
as
  l_val number;
  l_exec varchar2(100);
begin
  l_exec := 'select ' || l_seqname || '.nextval from dual';
  execute immediate l_exec into l_val;
  return l_val;
end;
```

Ecto.Adapters.SQL.query(Repo, "begin :1 := get_nextval('SEQ_1'); end;",[0])

** (Protocol.UndefinedError) protocol Enumerable not implemented for {1...} 

This error needs to be fixed.

**Comment by vstavskyi** [comment]
Error is fixed.
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/54559fb77d478dee3da663717565ee5d522f8c99)

**Comment by dougalcorn** [comment]
This is timely. I'm trying to do a `Repo.insert!(%User{name: "foo"})` but I'm getting an oracle error:

````
ORA-01008: not all variables bound

[debug] QUERY ERROR db=2.9ms queue=0.1ms
INSERT INTO web_ca.web_user (name) VALUES (:1) RETURN id INTO :id ["foo"]
````

When I instead do `Repo.insert!(%User{name: "foo", id: 1})` it works. I'm not clear at all how to get this sequence number and use it when doing an insert. I was kinda hoping it would be automatic.

**Comment by vstavskyi** [comment]
This error does not apply to Calling stored function. 
Using insert!/2 requires the explicit declaration of the returning @primary_key as OUT bind variable,  namely **{:out, 0}**.
>    * Using returning clause:
>       `{"insert into tabl values (tablid.nextval, sysdate) return id into :1"`, `[{:out, 0}]}`

**Comment by yukilau99** [comment]
Thanks for reply, you mean I can using Repo.insert!(%User{name: "foo"}, [returning: {"insert into tabl values (tablid.nextval, sysdate) return id into :1", [{:out, 0}]}] to insert the sequence val?

**Comment by vstavskyi** [comment]
`Repo.insert!(%User{name: "foo"})` without :id value returns autogenerated id using returning clause. But Oracle does not have SERIAL data type or IDENTITY (AUTO_INCREMENT) column property.
You can execute `Repo.insert!(%User{id:1, name: "foo"})`
You can use a sequence and a trigger to implement AUTO_INCREMENT functionality.
Unfortunatly `Repo.insert!(%User{name: "foo"}, returning: [:id, out: 0])` raises error at this time.

@yukilau99 I think, insert must be divided into parts.

**Comment by dougalcorn** [comment]
I ended up implementing `nextval` on MyApp.Repo:

````elixir
  def nextval(sequence) do
    case Ecto.Adapters.SQL.query(MyApp.Repo, "SELECT #{sequence}.nextval from dual") do
      {:ok, %{columns: ["NEXTVAL"], num_rows: 1, rows: [[next_id]]}} -> next_id
    end
  end
````

And then use it thusly: `Repo.insert!(%User{name: "foo", id: Repo.nextval("USER_SEQ")})` where `USER_SEQ` is setup as a sequence in the database.

**Comment by yukilau99** [comment]
I think I can close this issue now.

**Comment by tobiasdroessler** [comment]
I integrated the `nextval` function from @dougalcorn the following way into the (business model) -create function, see line 55 below. 

not sure if this is a proper way ... (?)  

```elixir
 52   def create_limit_class(attrs \\ %{}) do
 53     %LimitClass{}
 54     |> LimitClass.changeset(attrs)
 55     |> Ecto.Changeset.put_change( :id, Repo.nextval("USER_SEQ") )
 56     |> Repo.insert()
 57   end
```

@yukilau99 Could you may reopen that issue... to communicate a demand of integrating this basic Feature (without user defined Seq.) into the Database adapter oracle. I mean its was tagged as `enhancement` but is closed -- so it will not appear on the dev site of that lib.
