### ISSUE TITLE
Why a string save into DB will have one more '0' ?

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#29]
I have the code like this:
Coupons.create_coupon %{promotion_id: promotion_id, discount_amount: promotion.discount_amount, user_id: uid, status: "sss"}
to save coupon into DB, 
But when I get the record from DB, I got this?
%AdminApiEx.Coupons.Coupon{__meta__: #Ecto.Schema.Metadata<:loaded, "coupons">,
  balance: nil, code: nil, coupon_id: 25, coupon_type: nil, created_at: nil,
  discount_amount: nil, expiration: nil, got_time: nil, order_id: nil,
  printed: nil,
  promotion: #Ecto.Association.NotLoaded<association :promotion is not loaded>,
  promotion_id: 32, status: <<0, 115, 0, 115, 0, 115>>, used_time: nil,
  user_id: 1}

why the "status" became <<0, 115, 0, 115, 0, 115>>, not "sss"?

**Comment by vstavskyi** [comment]
Database stores NCHAR and NVARCHAR that way.
Execute in sqlplus ` select dump(status) from coupons where coupon_id=25` and you'll get the same result.

> When you create a table with an NCHAR column, you specify the column length as
> size characters, or more precisely, code points in the national character set. One code
> point has always 2 bytes in AL16UTF16 and from 1 to 3 bytes in UTF8, depending on
> the particular character encoded by the code point.

**Comment by vstavskyi** [comment]
I've got no zeros from my test database.

Database charset:
```
SELECT * FROM NLS_DATABASE_PARAMETERS
```
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	        AL32UTF8

Test table:
VAR NCHAR(20)  => field :var, :string
VAR2 NVARCHAR2(200)  => field :var2, :string

```
query = from e in Test
[debug]SELECT e0.var, e0.var2 FROM test e0 WHERE (e0.id = :1) [1]
```
Result:
[["ABC       ", "ABC"]]

**Comment by yukilau99** [comment]
I think the String was encoded before save into DB. the debug info was right.
[debug] QUERY OK db=9.1ms
SELECT SEQ_COUPONS.nextval FROM dual []
[info] %{balance: 22.2, code: "test1", coupon_id: 35, promotion_id: 271, user_id: 105554}
[debug] QUERY OK db=5.0ms
begin []
[debug] QUERY OK db=11.4ms
INSERT INTO coupons (balance,code,coupon_id,promotion_id,user_id) VALUES (:1,:2,:3,:4,:5) [22.2, "test1", 35, 271, 105554]

But the result in query is 't e s t 1'

**Comment by vstavskyi** [comment]
What's your database NLS parameters?

**Comment by yukilau99** [comment]
NLS_LANGUAGE	AMERICAN
NLS_TERRITORY	AMERICA
NLS_CURRENCY	$
NLS_ISO_CURRENCY	AMERICA
NLS_NUMERIC_CHARACTERS	.,
NLS_CHARACTERSET	UTF8
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_DATE_LANGUAGE	AMERICAN
NLS_SORT	BINARY
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY	$
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE
NLS_NCHAR_CHARACTERSET	UTF8
NLS_RDBMS_VERSION	11.2.0.3.0

**Comment by vstavskyi** [comment]
Your NLS_NCHAR_CHARACTERSET is set to UTF8, but in my environment it's set to UTF16.
Maybe this affects result and you need additional conversion on client.

**Comment by yukilau99** [comment]
The ' ' space will be remove If I change the NLS_NCHAR_CHARACTERSET to UTF16?

**Comment by vstavskyi** [comment]
You can try. And decode_data will work.
```
decode_data(Data, #format{data_type=DataType, charset=Charset}=ValueFormat)
    when Charset =:= ?AL16UTF16_CHARSET; Charset =:= ?AL32UTF8_CHARSET, DataType =:= ?TNS_TYPE_CLOB ->
    {Value, RestData} = decode_data(Data, ValueFormat#format{charset=?UTF8_CHARSET}),
    {xmerl_ucs:to_utf8(xmerl_ucs:from_utf16be(list_to_binary(Value))), RestData};
```
```
1> xmerl_ucs:to_utf8(xmerl_ucs:from_utf16be(<<0,115,0,115,0,115>>)).
"sss"
```

**Comment by yukilau99** [comment]
In my env, the string reading from DB is right, but when INSERT into DB is not right, 
for example:
iex(17)> Coupons.create_coupon(%{status: "test", promotion_id: 178, user_id: 105554})
iex(18)> Coupons.list_coupons  
[ %AdminApiEx.Coupons.Coupon{__meta__: #Ecto.Schema.Metadata<:loaded, "coupons">,
  coupon_id: 54, 
  promotion_id: 178, 
  status: <<0, 116, 0, 101, 0, 115, 0, 116>>, 
  user_id: 105554}]

You can see the STATUS value is not right.
And when I insert Chinese characters
iex(19)> Coupons.create_coupon(%{status: "你好", promotion_id: 178, user_id: 105554})
iex(20)> Coupons.list_coupons  
[%AdminApiEx.Coupons.Coupon{__meta__: #Ecto.Schema.Metadata<:loaded, "coupons">,
  promotion_id: 178, 
  status: "O`Y}", 
  used_time: nil, 
  user_id: 105554},

The status became "O`Y}".
[debug] QUERY OK db=13.0ms
INSERT INTO coupons (coupon_id,promotion_id,status,user_id) VALUES (:1,:2,:3,:4) [55, 178, "你好", 105554]
the debug sql was right, I think the String was decode before it inserted into DB.

**Comment by vstavskyi** [comment]
Please try execute simple test , like this:
```
defmodule Jamdb.OracleTest.Coupons do
  use Ecto.Schema
  import Ecto.Changeset
   
  @primary_key {:id, :integer, autogenerate: false}
  schema "coupons" do
    field :status, :string
  end

  def changeset(value, params \\ %{}) do
    value
    |> cast(params, [:id, :status])
  end  
    
end

defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo
  alias Jamdb.OracleTest.Erl


  test "a" do
    assert [] = TestRepo.all(from(c in Coupons, where: c.status=="你好"))
  end

  test "b" do
    changeset = Coupons.changeset(%Erl{}, %{id: 1, status: "你好" })
    assert %Erl{} = TestRepo.insert_or_update!(changeset)
  end

end

```

**Comment by yukilau99** [comment]
Sorry, I can not run the test at all when using oracle, 
I created a new project and prepare the test code:
    test "a" do
      assert [] = Repo.all(from(c in Coupons, where: c.status=="你好"))
    end

    test "b" do
      changeset = Coupons.changeset(%Erl{}, %{id: 1, status: "你好" })
      assert %Erl{} = Repo.insert_or_update!(changeset)
    end
And add the configuration in test.exs:
  config :oracle_test, OracleTest.Repo,
      name: HelloPhoenix.Repo,
      adapter: Ecto.Adapters.Jamdb.Oracle,
      port: 1521,
      username: "core",
      password: "2016",
      database: ":devdb1",
      hostname: "ora1.my.com",
      pool: Ecto.Adapters.SQL.Sandbox
But it raise the error bellow:
** (Mix) The database for OracleTest.Repo couldn't be created: false

And I don't understand what %Erl{} is, can you show me the code when connect to Oracle to run the test?

**Comment by yukilau99** [comment]
Hi, @vstavskyi 
When I execute the sql to check the sql sent to DB server, the results were null, I think the encoding of the value before insert into DB have been changed. 

select
s.sql_text,
b.name,b.position,b.dup_position,
b.value_string
from v$sql s, v$sql_bind_capture b
where s.hash_value=b.hash_value AND s.sql_text LIKE '%coupons%'

![wechatimg1](https://user-images.githubusercontent.com/460676/33260996-58d0b8e2-d39c-11e7-9aa0-2d6b8f8b6689.jpeg)

**Comment by vstavskyi** [comment]
I've corrected my test.
My schema name's Erl, in your case it's Coupons.

You can examine TCP Stream in Wireshark.

你好 :utf8: e4 bd a0 e5 a5  bd
你好 :utf16: 4f 60  59 7d

Insert without variable - **utf8** value:

00000674  00 6a 00 00 06 00 00 00  00 00 03 5e 00 02 81 21   .j...... ...^...!
00000684  00 01 01 25 01 01 0d 00  00 00 00 04 7f ff ff ff   ...%.... ........
00000694  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 00   ........ ........
000006A4  00 29 69 6e 73 65 72 74  20 69 6e 74 6f 20 45 52   .)insert  into ER
000006B4  4c 32 20 28 76 61 72 32  29 20 76 61 6c 75 65 73   L2 (var2 ) values
000006C4  20 28 27 **e4 bd a0 e5 a5  bd** 27 29 01 01 01 01 00    ('..... .').....
000006D4  00 00 00 00 00 00 00 00  00 00                     ........ ..

Insert with variable - **utf8** value:

000006DE  00 7f 00 00 06 00 00 00  00 00 03 5e 00 02 81 29   ........ ...^...)
000006EE  00 01 01 24 01 01 0d 00  00 00 00 04 7f ff ff ff   ...$.... ........
000006FE  01 01 01 00 00 00 00 00  00 00 00 00 01 00 00 00   ........ ........
0000070E  00 00 24 69 6e 73 65 72  74 20 69 6e 74 6f 20 45   ..$inser t into E
0000071E  52 4c 32 20 28 76 61 72  32 29 20 76 61 6c 75 65   RL2 (var 2) value
0000072E  73 20 28 3a 31 20 29 01  01 01 01 00 00 00 00 00   s (:1 ). ........
0000073E  00 00 00 00 00 00 01 03  00 00 02 0f a0 00 01 10   ........ ........
0000074E  00 00 02 03 67 01 00 07  06 **e4 bd a0 e5 a5 bd**      ....g... .......

Select  result  in my environment with NLS_NCHAR_CHARACTERSET	AL16UTF16  - **utf16** value:

00000AFD  00 b5 00 00 06 00 00 00  00 00 10 17 06 20 63 68   ........ ..... ch
    00000B0D  a6 06 e7 6f 6b b2 55 d8  76 03 0e ad 78 75 0b 1b   ...ok.U. v...xu..
    00000B1D  12 1e 07 01 c8 01 01 51  01 80 00 00 01 c8 00 02   .......Q ........
    00000B2D  10 00 00 00 02 07 d0 02  01 64 01 04 01 0c 04 56   ........ .d.....V
    00000B3D  41 52 32 00 00 00 00 01  07 07 78 75 0b 1b 12 1e   AR2..... ..xu....
    00000B4D  07 00 02 1f e8 01 0a 01  0a 00 06 22 01 01 00 01   ........ ..."....
    00000B5D  0f 00 00 00 07 04 **4f 60  59 7d** 08 01 06 03 76 73   ......**O` Y}.**...vs
    00000B6D  e6 00 01 02 00 00 00 00  00 00 04 01 01 01 04 01   ........ ........
    00000B7D  01 02 05 7b 00 00 01 02  01 11 03 00 00 00 00 00   ...{.... ........
    00000B8D  00 00 00 00 00 00 00 00  00 01 01 19 4f 52 41 2d   ........ ....ORA-
    00000B9D  30 31 34 30 33 3a 20 6e  6f 20 64 61 74 61 20 66   01403: n o data f
    00000BAD  6f 75 6e 64 0a                                     ound.

**Comment by vstavskyi** [comment]
Have you tried using the N' modifier for the string literal?
```
defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo

  test "query" do
    assert [] = TestRepo.query("INSERT INTO coupons (coupon_id,promotion_id,status,user_id) VALUES (:1, :2, N'你好', :3)", [55, 178, 105554])
  end
end
```

**Comment by yukilau99** [comment]
Yes, Wireshark captured the package shows that every alphabet was insert '00' before inserted into DB.
iex(21)> Coupons.create_coupon(%{promotion_id: 2222, user_id: 3223, status: "abcdefg"})
[debug] QUERY OK db=2.4ms queue=0.1ms
SELECT SEQ_COUPONS.nextval from dual []
[info] %{coupon_id: 75, promotion_id: 2222, status: "abcdefg", user_id: 3223}
[debug] QUERY OK db=1.1ms
begin []
[debug] QUERY OK db=1.6ms
INSERT INTO coupons (coupon_id,promotion_id,status,user_id) VALUES (:1,:2,:3,:4) [75, 2222, "abcdefg", 3223]
[debug] QUERY OK db=15.2ms
commit []
{:ok,
 %AdminApiEx.Coupons.Coupon{__meta__: #Ecto.Schema.Metadata<:loaded, "coupons">,
  balance: nil, code: nil, coupon_id: 75, coupon_type: nil, created_at: nil,
  discount_amount: nil, expiration: nil, got_time: nil, order_id: nil,
  printed: nil,
  promotion: #Ecto.Association.NotLoaded<association :promotion is not loaded>,
  promotion_id: 2222, status: "abcdefg", used_time: nil, user_id: 3223}}

The 'abcdefg' became ' a b c d e f g'
![wechatimg1](https://user-images.githubusercontent.com/460676/33300289-78be833a-d42a-11e7-8ef9-b9d32c610fb2.jpeg)

My env:

Erl 20, erts: 9.1, elixir: 1.5.2

**Comment by vstavskyi** [comment]
I have the same in my env. This's utf16 encoding. Database stores it also in utf16. 
But in my bash shell with utf8 locale result is shown in utf8 encoding just fine.

[a](http://www.fileformat.info/info/unicode/char/0061/index.htm) UTF-16 (hex) | 0x0061

`select dump(var2) from erl2`
Typ=1 Len=4: 79,96,89,125
Typ=1 Len=4: 79,96,89,125
Typ=1 Len=8: **0,97,0,98,0,99,0,100**
Typ=1 Len=8: **0,97,0,98,0,99,0,100**

0000080C  00 96 00 00 06 00 00 00  00 00 03 5e 00 02 81 29   ........ ...^...)
0000081C  00 01 01 29 01 01 0d 00  00 00 00 04 7f ff ff ff   ...).... ........
0000082C  01 01 02 00 00 00 00 00  00 00 00 00 01 00 00 00   ........ ........
0000083C  00 00 29 49 4e 53 45 52  54 20 49 4e 54 4f 20 65   ..)INSER T INTO e
0000084C  72 6c 32 20 28 69 64 2c  76 61 72 32 29 20 56 41   rl2 (id, var2) VA
0000085C  4c 55 45 53 20 28 3a 31  2c 3a 32 29 01 01 01 01   LUES (:1 ,:2)....
0000086C  00 00 00 00 00 00 00 00  00 00 00 02 03 00 00 01   ........ ........
0000087C  16 00 00 00 00 00 01 00  01 03 00 00 02 0f a0 00   ........ ........
0000088C  01 10 00 00 02 07 d0 02  00 07 02 c1 03 08 **00 61**   ........ .......a
0000089C  **00 62 00 63 00 64**                                  .b.c.d




```
defmodule Jamdb.OracleTest.Erl do
  use Ecto.Schema
  import Ecto.Changeset
   
  @primary_key {:id, :float, autogenerate: false}
  schema "erl2" do
    field :var2, :string
  end

  def changeset(value, params \\ %{}) do
    value
    |> cast(params, [:id, :var2])
  end  
    
end

defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo
  alias Jamdb.OracleTest.Erl


  test "a" do
    assert [] = TestRepo.all(from(e in Erl, where: e.var2=="你好"))
  end

  test "b" do
    changeset = Erl.changeset(%Erl{}, %{id: 2.0, var2: "你好" })
    assert %Erl{} = TestRepo.insert_or_update!(changeset)
  end

  test "c" do
    changeset = Erl.changeset(%Erl{}, %{id: 2.0, var2: "abcd" })
    assert %Erl{} = TestRepo.insert_or_update!(changeset)
  end

  test "d" do
    assert %Erl{} = TestRepo.query("INSERT INTO erl2 (id, var2) VALUES (:1, N'你好')", [2])
  end

  test "e" do
    assert %Erl{} = TestRepo.query("INSERT INTO erl2 (id, var2) VALUES (:1, 'abcd')", [2])
  end

  test "f" do
    var2 = "你好"
    assert [] = TestRepo.all(from(e in Erl, where: e.var2==^var2))
  end

  test "z" do
    var2 = "abcd"
    assert [] = TestRepo.all(from(e in Erl, where: e.var2==^var2))
  end

end
```


```
15:29:25.320 [debug] QUERY OK db=12.2ms queue=1.3ms
INSERT INTO erl2 (id, var2) VALUES (:1, 'abcd') [2]

15:29:25.343 [debug] QUERY OK source="erl2" db=0.5ms queue=0.1ms
SELECT e0.id, e0.var2 FROM erl2 e0 WHERE (e0.var2 = '你好') []


  1) test e (Jamdb.OracleTest)
     test/test3.exs:42
     match (=) failed
     code:  %Erl{} = TestRepo.query("INSERT INTO erl2 (id, var2) VALUES (:1, 'abcd')", [2])
     right: {:ok, %{num_rows: 1, rows: nil}}
     stacktrace:
       test/test3.exs:43: (test)

.
15:29:25.350 [debug] QUERY OK source="erl2" db=2.4ms
SELECT e0.id, e0.var2 FROM erl2 e0 WHERE (e0.var2 = :1) ["abcd"]


  2) test z (Jamdb.OracleTest)
     test/test3.exs:51
     match (=) failed
     code:  [] = TestRepo.all(from(e in Erl, where: e.var2() == ^var2))
     right: [%Jamdb.OracleTest.Erl{__meta__: #Ecto.Schema.Metadata<:loaded, "erl2">,
              id: 2.0, var2: "abcd"}]
     stacktrace:
       test/test3.exs:53: (test)


15:29:25.368 [debug] QUERY OK db=10.5ms queue=0.1ms
INSERT INTO erl2 (id,var2) VALUES (:1,:2) [2.0, "abcd"]                                                  
.
15:29:25.377 [debug] QUERY OK db=7.9ms queue=0.1ms                                                       
INSERT INTO erl2 (id,var2) VALUES (:1,:2) [2.0, "你好"]                                                  
.
15:29:25.385 [debug] QUERY OK db=8.0ms queue=0.1ms                                                       
INSERT INTO erl2 (id, var2) VALUES (:1, N'你好') [2]                                                     


  3) test d (Jamdb.OracleTest)
     test/test3.exs:38
     match (=) failed
     code:  %Erl{} = TestRepo.query("INSERT INTO erl2 (id, var2) VALUES (:1, N'你好')", [2])
     right: {:ok, %{num_rows: 1, rows: nil}}
     stacktrace:
       test/test3.exs:39: (test)


15:29:25.386 [debug] QUERY OK source="erl2" db=0.5ms
SELECT e0.id, e0.var2 FROM erl2 e0 WHERE (e0.var2 = :1) ["你好"]


  4) test f (Jamdb.OracleTest)
     test/test3.exs:46
     match (=) failed
     code:  [] = TestRepo.all(from(e in Erl, where: e.var2() == ^var2))
     right: [%Jamdb.OracleTest.Erl{__meta__: #Ecto.Schema.Metadata<:loaded, "erl2">,
              id: 2.0, var2: "你好"},
             %Jamdb.OracleTest.Erl{__meta__: #Ecto.Schema.Metadata<:loaded, "erl2">,
              id: 2.0, var2: "你好"}]
     stacktrace:
       test/test3.exs:48: (test)



Finished in 0.2 seconds
7 tests, 4 failures

Randomized with seed 152992

```

**Comment by yukilau99** [comment]
How to change the encoding to be UTF8?

**Comment by vstavskyi** [comment]
"abcd" is a binary in erlang terms, 'abcd' is a list.

So. encode_token for binary is working.

```
encode_token(rxd, Data) when is_list(Data) -> encode_chr(Data);
encode_token(rxd, Data) when is_binary(Data) -> encode_chr(unicode:characters_to_binary(Data, utf8, utf16));
```

```
1> unicode:characters_to_binary(<<"abcd">>, utf8, utf16).            
<<0,97,0,98,0,99,0,100>>
```

We need custom ecto type and convert values from string into charlist.

**Comment by vstavskyi** [comment]
Type Tagged сan be processed:
```
defp encode(%Ecto.Query.Tagged{value: elem}) when is_binary(elem), do: elem |> to_charlist
defp encode(%Ecto.Query.Tagged{value: elem}), do: elem
```
or even
```
defp encode(%Ecto.Query.Tagged{value: elem}), do: elem |> to_charlist
```

**Comment by yukilau99** [comment]
I don't want to change your erl source code in case of upgrade version. 
I don't understand the Type Tagged, where to place this code?

**Comment by vstavskyi** [comment]
New parameter **charset** was added.
If its value is a member of ["al16utf16","ja16euc","zhs16gbk","zht16big5","zht16mswin950"],
then string variable will be converted to utf16 in query packet.
If this parameter isn't set or set to any other value, then string variable remains in utf8 encoding.
Charset names can be found in jamdb_oracle.hrl
`charset: "al16utf16"`

Type **{:array, :integer}**  was tested for RAW and BLOB.
Value must be  base16 encoded charlist.
```
field :raw, {:array, :integer}
.....
raw = 'E799BE'
```

[commit](https://github.com/erlangbureau/jamdb_oracle/commit/8620d7e7316f0cbd5bb935a2db31694dcc3495d0)

**Comment by yukilau99** [comment]
Perfect! Thank you very much.

**Comment by vstavskyi** [comment]
Yes, next week.
