### ISSUE TITLE
"in" operator does not work when using an Array variable in sql

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#30]
Environment

Elixir version (elixir -v) : 1.5.0
Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL: 9.4
Ecto version (mix deps): 2.2.6
Database adapter and version (mix deps): Ecto.Adapters.Postgres,
Operating system: Mac Sierra
Current behavior

When I use a ^variable in "where", the query sql is became "= ANY($1)"
iex(6)> ids=[1,2]
[1, 2]
iex(7)> from(p in Promotion, select: p, where: p.promotion_id in ^ids) |> Repo.all
[debug] QUERY OK source="promotions" db=2.2ms queue=0.1ms
SELECT p0."id", p0."name", p0."promotion_id", p0."status", p0."inserted_at", p0."updated_at" FROM "promotions" AS p0 WHERE (p0."promotion_id" = ANY($1)) [[1, 2]]

And if I wrote the array in query directly, it works.
from(p in Promotion, select: p, where: p.promotion_id in [1, 2]) |> Repo.all
[debug] QUERY OK source="promotions" db=1.4ms
SELECT p0."id", p0."name", p0."promotion_id", p0."status", p0."inserted_at", p0."updated_at" FROM "promotions" AS p0 WHERE (p0."promotion_id" IN (1,2)) []

And it works on ECTO version of 2.1.4

Expected behavior

Cast the "where: p.promotion_id in ^ids" to the right sql.

**Comment by vstavskyi** [comment]
Please test last [commit](https://github.com/erlangbureau/jamdb_oracle/commit/3c408cc602be3c5976e60bf01f69f5c995fc0e0c)

**Comment by yukilau99** [comment]
Bellow is the operator, still met the error:
iex(11)> cids=[171, 172]
[171, 172]
iex(12)> from(p in Promotion, select: p, where: p.promotion_id in ^cids) |> Repo.all
ORA-01006: bind variable does not exist

[debug] QUERY ERROR source="promotions" db=8.0ms
SELECT p0.promotion_id, p0.name, p0.type_id, p0.slogon, p0.logo_url, p0.circulation, p0.discount_amount, p0.discount_percent, p0.meet_count, p0.meet_amount, p0.first_n_count, p0.not_exceed_amount, p0.first_n_orders, p0.generated_coupon, p0.status_id, p0.created_at, p0.updated_at, p0.created_by, p0.active_begin, p0.active_end, p0.use_for, p0.template_id, p0.reusable, p0.expiration FROM promotions p0 WHERE (p0.promotion_id = ANY(:1)) [171, 172]
** (DBConnection.ConnectionError) %{code: 1006, message: 'ORA-01006: bind variable does not exist\n'}
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:165: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
            (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
            (ecto) lib/ecto/adapters/sql.ex:448: Ecto.Adapters.SQL.sql_call!/6
            (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.do_execute/6
            (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
            (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4

And I saw the code at line 266 in jamdb_oracle_query.ex 
  defp expr({:in, _, [left, right]}, sources, query) when is_list(right) do
    args = intersperse_map(right, ?,, &expr(&1, sources, query))
    [expr(left, sources, query), " IN (", args, ?)]
  end

seems it was not be cast to "IN " query.

**Comment by yukilau99** [comment]
Yes, fixed, please push to hex.pm.

**Comment by vstavskyi** [comment]
For multiple conditions I'd like to realize consecutive numbering.
Now: (:1,:2,:3) ... (:1,:2,:3) ...
Must be:  (:1,:2,:3,:4,:5,:6,....)

**Comment by yukilau99** [comment]
Yes, that will be fine

**Comment by vstavskyi** [comment]
I'm still thinking what to do with multiple conditions. It seems to work without errors.
```
num = 100
numb = 100.0
nums = [num,num,num,101]
nums2 = [num,101]
query = from e in JconnMix.Erl, select: [e.var2], where: e.num == ^numb or e.num == ^numb or e.num in ^nums or e.num in ^nums2 or e.num == ^numb or e.num == ^numb or e.num in ^nums or e.num in ^nums2


[debug] QUERY OK source="erl4" db=4.9ms
SELECT e0.var2 FROM erl4 e0 WHERE ((((((((e0.num = :1) OR (e0.num = :2)) OR e0.num IN (:1,:2,:3,:4)) OR e0.num IN (:1,:2)) OR (e0.num = :5)) OR (e0.num = :6)) OR e0.num IN (:1,:2,:3,:4)) OR e0.num IN (:1,:2)) [100.0, 100.0, 100.0, 100.0, 100.0, 101.0, 100.0, 101.0, 100.0, 100.0, 100.0, 100.0, 100.0, 101.0, 100.0, 101.0]
```
