### ISSUE TITLE
crc32 error when there is unicode in sql.

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#32]
Repo.all(from(c in Coupon, where: c.status=="你好"))
[debug] QUERY ERROR source="coupons" db=126.3ms
SELECT c0.coupon_id, c0.balance, c0.code, c0.coupon_type, c0.discount_amount, c0.order_id, c0.printed, c0.status, c0.user_id, c0.got_time, c0.used_time, c0.expiration, c0.created_at, c0.promotion_id FROM coupons c0 WHERE (c0.status = '你好') []
** (DBConnection.ConnectionError) [{:erlang, :crc32, [[83, 69, 76, 69, 67, 84, 32, 99, 48, 46, 99, 111, 117, 112, 111, 110, 95, 105, 100, 44, 32, 99, 48, 46, 98, 97, 108, 97, 110, 99, 101, 44, 32, 99, 48, 46, 99, 111, 100, 101, 44, 32, 99, 48, 46, 99, ...]], []}, {:jamdb_oracle_conn, :get_param, 2, [file: 'src/jamdb_oracle_conn.erl', line: 305]}, {:jamdb_oracle_conn, :get_param, 2, [file: 'src/jamdb_oracle_conn.erl', line: 316]}, {:jamdb_oracle_conn, :send_req, 3, [file: 'src/jamdb_oracle_conn.erl', line: 228]}, {:jamdb_oracle_conn, :sql_query, 3, [file: 'src/jamdb_oracle_conn.erl', line: 110]}, {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 45]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 636]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 665]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:165: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4

**Comment by vstavskyi** [comment]
Hello there ;)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/964b5cd5d7c640f85e1a92d80d68b4a461d578ce)
 The error wouldn't have been fixed if variable was used.
```
status = "你好"
Repo.all(from(c in Coupon, where: c.status==^status))
```

**Comment by yukilau99** [comment]
Cool, fixed. Thank you very much!
