### ISSUE TITLE
Can not login in with right user info

### ISSUE THREAD

**Issue by xsir99** [erlangbureau/jamdb_oracle#33]
I get an error `ORA-01017: invalid username/password; logon denied`  
But, acctually I put the right username and password(I can login in with DBeaver)
With debugging , I find `AUTH_VFR_DATA` return `undefined` ...
here is oracle version info
```
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production
```
and I also use wireshark get  this when connect with jamdb_oracle

![_008](https://user-images.githubusercontent.com/9145595/33300865-8aaddea8-d42d-11e7-8611-25d20280a7db.png)  

and connect with other tool(successful)

![_009](https://user-images.githubusercontent.com/9145595/33301176-469bc4c6-d42f-11e7-8d3b-850bf15ed642.png)

Is there something wrong?

**Comment by yukilau99** [comment]
Oracle 11g credentials are case sensitive. change the password and have a try.

**Comment by vstavskyi** [comment]
Maybe problem with username?
Check username in sending packet, for example my test username KOPL_UA:

00000507  00 82 00 00 06 00 00 00  00 00 03 76 00 01 01 07   ........ ...v....
00000517  01 01 01 01 04 01 01 07  **6b 6f 70 6c 5f 75 61** 01   ........ **kopl_ua**.
00000527  0f 0f 41 55 54 48 5f 50  52 4f 47 52 41 4d 5f 4e   ..AUTH_P ROGRAM_N
00000537  4d 01 07 07 70 72 69 6d  65 72 6c 00 01 0c 0c 41   M...prim erl....A
00000547  55 54 48 5f 4d 41 43 48  49 4e 45 01 09 09 70 72   UTH_MACH INE...pr
00000557  6f 63 2d 6d 69 6b 65 00  01 08 08 41 55 54 48 5f   oc-mike. ...AUTH_
00000567  50 49 44 01 05 05 32 30  32 34 39 00 01 08 08 41   PID...20 249....A
00000577  55 54 48 5f 53 49 44 01  07 07 **6b 6f 70 6c 5f 75**   UTH_SID. ..**kopl_u**
00000587  **61** 00                                              **a**.

**Comment by xsir99** [comment]
@yukilau99  @vstavskyi  Thanks for the reply！
I don't think is problem of username or password, my username is `apps`:  

![_011](https://user-images.githubusercontent.com/9145595/33415509-1886f8b8-d5d2-11e7-9974-6ed42807b36d.png)

I check the source code 
```erlang
encode_record(auth, EnvOpts, Sess, Salt) ->
    User            = proplists:get_value(user, EnvOpts),
    Pass            = proplists:get_value(password, EnvOpts),
    Role            = proplists:get_value(role, EnvOpts, 0), 
    Prelim          = proplists:get_value(prelim, EnvOpts, 0),
    {AuthPass, AuthSess, KeyConn} = 
    case Salt of
        undefined -> jamdb_oracle_crypt:o5logon(Sess, User, Pass, 128);
        _ -> jamdb_oracle_crypt:o5logon(Sess, Salt, Pass, 192)
    end,
```
https://github.com/erlangbureau/jamdb_oracle/blob/964b5cd5d7c640f85e1a92d80d68b4a461d578ce/src/jamdb_oracle_tns_encoder.erl#L25

**Comment by vstavskyi** [comment]
Yes, it's old method for 10g.
Please post full successful connection dump in pcap format.
I'll try ugrade my test 11g to 11.2.0.4 and test connection asap.

**Comment by xsir99** [comment]
Here is the dump files, include connection successful and fail 
[dump.tar.gz](https://github.com/erlangbureau/jamdb_oracle/files/1520032/dump.tar.gz)

**Comment by vstavskyi** [comment]
in fail dump HOST=127.0.0.1,  in success is not

**Comment by xsir99** [comment]
Yes, right, fail one is connect with jame_oracle host=127.0.0.1,  and success is connect with other tool in  docker and host=192.168.1.7  
the oracle env was  mapped to my local by ssh

**Comment by vstavskyi** [comment]
maybe server has specific configuration?
try replace body of encode_record(dty, _EnvOpts) in jamdb_oracle_tns_encoder.erl with this code:
```
    <<
    ?TTI_DTY,
    (encode_ub2(?UTF8_CHARSET))/binary,	%cli in charset
    (encode_ub2(?UTF8_CHARSET))/binary,	%cli out charset
    131,42,6,1,1,1,111,1,1,9,1,1,1,1,1,1,1,127,255,3,12,3,3,1,1,255,1,255,255,1,11,1,
    1,255,1,6,9,98,1,127,4,0,3,13,7,2,1,0,0,24,0,7,128,0,0,0,60,60,60,128,0,0,0,
    0,0,0,26,208,7
    >>;
```

**Comment by vstavskyi** [comment]
Have you tried  to connect with JDBC drivers?

**Comment by xsir99** [comment]
It is not work,  with new encode code ...
Yes I  tried to connect with JDBC , and it's OK

**Comment by vstavskyi** [comment]
post dump from jdbc with host=127.0.0.1, please

**Comment by xsir99** [comment]
@vstavskyi 
[dump.tar.gz](https://github.com/erlangbureau/jamdb_oracle/files/1526167/dump.tar.gz)

**Comment by vstavskyi** [comment]
Yes, AUTH_VFR_DATA is empty, but why?
Could you check SQLNET.ORA?
Is there are any additional config parameters? For example:
`SQLNET.ALLOWED_LOGON_VERSION=10
`

Try first full version of encode_record(dty, _EnvOpts)
```
   <<
    ?TTI_DTY,
    (encode_ub2(?UTF8_CHARSET))/binary,	%cli in charset
    (encode_ub2(?UTF8_CHARSET))/binary,	%cli out charset
    2,
    38,6,1,0,0,10,1,1,6,1,1,1,1,1,1,0,41,144,3,7,3,0,1,0,79,1,55,4,0,0,0,0,12,0,0,6,0,1,1,
    7,2,0,0,0,0,0,0,
    1,1,1,0,2,2,10,0,8,8,1,0,12,12,10,0,23,23,1,0,24,24,1,0,
    25,25,1,0,26,26,1,0,27,27,1,0,28,28,1,0,29,29,1,0,30,30,1,0,31,31,1,0,
    32,32,1,0,33,33,1,0,
    10,10,1,0,11,11,1,0,40,
    40,1,0,41,41,1,0,117,117,1,0,120,120,1,0,34,34,1,0,35,35,1,0,36,36,1,0,37,37,1,0,
    38,38,1,0,42,42,1,0,43,43,1,0,44,44,1,0,45,45,1,0,46,46,1,0,47,47,1,0,48,48,1,0,
    49,49,1,0,50,50,1,0,51,51,1,0,52,52,1,0,53,53,1,0,54,54,1,0,55,55,1,0,56,56,1,0,
    57,57,1,0,59,59,1,0,60,60,1,0,61,61,1,0,62,62,1,0,63,63,1,0,64,64,1,0,65,65,1,0,
    66,66,1,0,67,67,1,0,71,71,1,0,72,72,1,0,73,73,1,0,75,75,1,0,77,77,1,0,78,78,1,0,
    79,79,1,0,80,80,1,0,81,81,1,0,82,82,1,0,83,83,1,0,84,84,1,0,85,85,1,0,86,86,1,0,
    87,87,1,0,88,88,1,0,89,89,1,0,90,90,1,0,92,92,1,0,93,93,1,0,98,98,1,0,99,99,1,0,
    103,103,1,0,107,107,1,0,124,124,1,0,125,125,1,0,126,126,1,0,127,127,1,0,128,128,1,0,
    129,129,1,0,130,130,1,0,131,131,1,0,132,132,1,0,133,133,1,0,134,134,1,0,135,135,1,0,
    137,137,1,0,138,138,1,0,139,139,1,0,140,140,1,0,141,141,1,0,142,142,1,0,143,143,1,0,
    144,144,1,0,145,145,1,0,148,148,1,0,149,149,1,0,150,150,1,0,151,151,1,0,157,157,1,0,
    158,158,1,0,159,159,1,0,160,160,1,0,161,161,1,0,162,162,1,0,163,163,1,0,164,164,1,0,
    165,165,1,0,166,166,1,0,167,167,1,0,168,168,1,0,169,169,1,0,170,170,1,0,171,171,1,0,
    173,173,1,0,174,174,1,0,175,175,1,0,176,176,1,0,177,177,1,0,193,193,1,0,194,194,1,0,
    198,198,1,0,199,199,1,0,200,200,1,0,201,201,1,0,202,202,1,0,203,203,1,0,204,204,1,0,
    205,205,1,0,206,206,1,0,207,207,1,0,210,210,1,0,211,211,1,0,212,212,1,0,213,213,1,0,
    214,214,1,0,215,215,1,0,216,216,1,0,217,217,1,0,218,218,1,0,219,219,1,0,220,220,1,0,
    221,221,1,0,222,222,1,0,223,223,1,0,224,224,1,0,225,225,1,0,226,226,1,0,227,227,1,0,
    228,228,1,0,229,229,1,0,230,230,1,0,234,234,1,0,235,235,1,0,236,236,1,0,237,237,1,0,
    238,238,1,0,239,239,1,0,240,240,1,0,242,242,1,0,243,243,1,0,244,244,1,0,245,245,1,0,
    246,246,1,0,253,253,1,0,254,254,1,0,1,1,1,0,2,2,1,0,4,4,1,0,5,5,1,0,6,6,1,0,7,7,1,0,
    8,8,1,0,9,9,1,0,10,10,1,0,11,11,1,0,12,12,1,0,13,13,1,0,14,14,1,0,15,15,1,0,16,16,1,0,
    17,17,1,0,18,18,1,0,19,19,1,0,20,20,1,0,21,21,1,0,22,22,1,0,23,23,1,0,24,24,1,0,
    25,25,1,0,26,26,1,0,27,27,1,0,28,28,1,0,29,29,1,0,30,30,1,0,31,31,1,0,48,48,1,0,
    53,53,1,0,60,60,1,0,61,61,1,0,62,62,1,0,63,63,1,0,64,64,1,0,66,66,1,0,68,68,1,0,
    69,69,1,0,70,70,1,0,71,71,1,0,72,72,1,0,73,73,1,0,
    3,2,10,0,4,2,10,0,5,1,1,0,6,2,10,0,7,2,10,0,9,1,1,0,13,0,14,0,15,23,1,0,16,0,17,0,
    18,0,19,0,20,0,21,0,22,0,39,120,1,0,58,0,68,2,10,0,69,0,70,0,74,0,76,0,91,2,10,0,
    94,1,1,0,95,23,1,0,96,96,1,0,97,96,1,0,100,100,1,0,101,101,1,0,102,102,1,0,
    104,11,1,0,105,0,106,106,1,0,108,109,1,0,109,109,1,0,110,111,1,0,111,111,1,0,
    112,112,1,0,113,113,1,0,114,114,1,0,115,115,1,0,116,102,1,0,118,0,119,0,121,0,122,0,
    123,0,136,0,146,146,1,0,147,0,152,2,10,0,153,2,10,0,154,2,10,0,155,1,1,0,156,12,10,0,
    172,2,10,0,178,178,1,0,179,179,1,0,180,180,1,0,181,181,1,0,182,182,1,0,183,183,1,0,
    184,12,10,0,185,185,1,0,186,186,1,0,187,187,1,0,188,188,1,0,189,189,1,0,190,190,1,0,
    191,0,192,0,195,112,1,0,196,113,1,0,197,114,1,0,208,208,1,0,209,0,231,231,1,0,
    232,231,1,0,233,233,1,0,241,109,1,0,3,0,78,78,1,0,79,79,1,0,80,80,1,0,0
    >>;

```

**Comment by vstavskyi** [comment]
Create new user and try to connect. Maybe old users were migrated from previuos database version.

**Comment by vstavskyi** [comment]
Play with system tables:
```
select password,spare4 from user$ where name='SCOTT'
----------
20B2D140932F1C54	S:2B9FD12F39032290703BD508E8BFECC1E58CE2689296325EE7CD47A35F7F

select password_versions from dba_users where username='SCOTT'
----------
10G 11G 
```
set spare4 to null
```
update user$ set spare4=null where name='SCOTT'

select password,spare4 from user$ where name='SCOTT'
----------
20B2D140932F1C54	null

select password_versions from dba_users where username='SCOTT'
----------
10G
```
**attempt to connect**

set password
```
alter user scott identified by tiger

select password,spare4 from user$ where name='SCOTT'
----------
20B2D140932F1C54	S:F67A5C1DB7105016094D80A3153EE98F74FE1739021185492C085AEC50F0

select password_versions from dba_users where username='SCOTT'
----------
10G 11G 
```
**attempt to connect**

set spare4 to null
```
update user$ set spare4=null where name='scott'
```
**attempt to connect**

**Comment by xsir99** [comment]
Em...I do not have permission to do that,  because  it's customer's env.
Do you know how to reproduce this issue on my local?

**Comment by enpedasi** [comment]
Repot on Logon availability.
[NG : ORA-01017]
AWS RDS for Oracle 11g 11.2.0.4.0 Standard Edition
AWS EC2 Oracle 12c 12.1.0.2.0  Windows Server 2008 [SQLNET.Ora] ALLOWED_LOGON_VERSION=8

[OK]
Oracle 11g XE on Centos 6
Oracle 11g standard edition 11.2.0.1.0 on Centos 6
Oracle 11g standard edition 11.2.0.1.0 on Windors Server 2012
Oracle 10g Standard Edition 10.2.0.4.0 on Windows Server 2008

**Comment by vstavskyi** [comment]
I fully support answer from [this](https://stackoverflow.com/questions/29696059/oracle-11g-r2-ora-01017-invalid-username-password-logon-denied-when-connecting) post when database was migrated from 9i:
> set the logon version to 10:
> ALLOWED_LOGON_VERSION=10
> regenerate the user's password (to re-generate the verifiers):
> ALTER USER user IDENFIFIED BY "newpassword";

**Comment by vstavskyi** [comment]
Please test 12c password version implementation 
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/f485bbc5ad170d227ec028dfeb6f97c134276c1b)

**Comment by enpedasi** [comment]
thank you for reply and the improvement.
I tried with the following settings, but I could not log in.
(oracle 12.1.0.2.0, aws rds 11.2.0.4)

```elixir
defp deps do
  [
    {:jamdb_oracle, git: "https://github.com/erlangbureau/jamdb_oracle.git", override: true},
  ]
```

**Comment by vstavskyi** [comment]
The spare4 column from the sys.user$ table stores user password hashes.
The S: part is 11g hash.
The T: part is 12c hash.
Old 10g hash is stored in password column.

```
alter user scott identified by tiger

select spare4 from sys.user$ where name='SCOTT';
--------------------------------------------------------------------------------
S:C5504FC94F89F44BF6BC4FDC9FC6A720870AF0DE1BE44FABC985924558EE;T:5A44EAD353340B0
B60C9236CCD0A3BFC7BDE9438E4A86B7C7AC71D5EC9BB886DBFCF02F9D239CCCF54FBD8563E3ED9D
7550C404D1A5BC33DF30487A0A1AC9001BDF411CFE6DD1FAB6E0B4B40BD8F3F6D
```

In my env with Database 12c Release 12.2.0.1 both S: and T: parts exist, SQLNET.ALLOWED_LOGON_VERSION_SERVER is default (8,10,11,12 values also probed) and last commit is working correctly.


With SQLNET.ALLOWED_LOGON_VERSION_SERVER=**12a** and SQLNET.ALLOWED_LOGON_VERSION_CLIENT=**12a** the spare4 value no longer has the S: part, only the T:

```
alter user scott identified by tiger

select spare4 from sys.user$ where name='SCOTT';
--------------------------------------------------------------------------------
T:5A44EAD353340B0B60C9236CCD0A3BFC7BDE9438E4A86B7C7AC71D5EC9BB886DBFCF02F9D239CCCF54FBD8563E3ED9D
7550C404D1A5BC33DF30487A0A1AC9001BDF411CFE6DD1FAB6E0B4B40BD8F3F6D
```

After migratation from 9 or 10g  the S: part is not exists in spare4.
Release 11.2.0.2 uses old 10g procedure with 128-bit keys.
But after 11.2.0.4 procedure was changed and I don't know exactly how.
That's why you cannot login.

**Comment by orz--** [comment]
I don't know erlang, I'm sorry.
But I'm interested in this event.

1.I want to know ORA-1017 occurred env's user$ info.
2.As if there is Oracle11.2.0.4's test environment, please try SQLNET.ALLOWED_LOGON_VERSION=12(maybe security reasons) 
 to sqlnet.ora and using newest jamdb_oracle.
3.Is jamdb_oracle processing a password string?(triming or padding and so on)
4.Every ORA-1017 occurred env's using HOST=127.0.01 ?

**Comment by braulio** [comment]
Hello, any news?

**Comment by vstavskyi** [comment]
finally
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/41ed8917bb993a1537ad40228c6ada471fb47c8b)
