### ISSUE TITLE
Can I configure the adapter to log sql statements?

### ISSUE THREAD

**Issue by dougalcorn** [erlangbureau/jamdb_oracle#34]
I'd like to have a debug log mode that would let me see all the sql that jamdb is running. I'm accessing this from Ecto. I'm not exactly sure if I need this configured in Ecto somewhere, but I kinda feel like it should be available at the adapter level.

**Comment by vstavskyi** [comment]
Config exampe from [this post](https://stackoverflow.com/questions/30297825/disable-elixir-ecto-debug-output)
`config :logger, level: :debug`
All statements are visible. 

You can edit jamdb_oracle_tns_decoder.erl as you like.
```
decode_token(<<Token, Data/binary>>, Acc) ->
  io:format("~p~n", [{Token, Data, Acc}]),
```

**Comment by dougalcorn** [comment]
The second answer on that page seems to be the right one. When I do this:

    config :logger, level: debug

in tests, I see my cowboy server starting up; but no sql statements. However, when I configure the Repo:

````
config :my_app, MyApp.Repo
  loggers: [{Ecto.LogEntry, :log, [:info]}]
````

I'm actually able to see the sql statements that are generated.
