### ISSUE TITLE
Can't seem to use schema prefix

### ISSUE THREAD

**Issue by dougalcorn** [erlangbureau/jamdb_oracle#35]
So far, my schema has been the default schema for the user I login to oracle as. I've defined my modules like this:

```elixir
defmodule MyApp.MyModel do
  @schema_prefix "web_ca"

  schema "table_name" do
    field :name, :string
  end
end
```

So far everything has worked well. However, now need to support multiple schemas. Re-reading the documentation on `@schema_prefix`, I'm not sure it's doing what I want it to do. The documentation says:

> @schema_prefix - configures the schema prefix. Defaults to nil, which generates structs and queries without prefix. When set, the prefix will be used by every built struct and on queries where the current schema is used in from (and only from exclusively). If a schema is used as a join or part of an assoc, @schema_prefix won’t be obeyed. In PostgreSQL, the prefix is called “SCHEMA” (typically set via Postgres’ search_path). In MySQL the prefix points to databases.

With the proper logging, I see something like this when I try to insert:

````
INSERT INTO table_name (id,name) VALUES (:1,:2) [72, "bob"]
````

I expected it to show the prefix here, but it doesn't. Maybe the answer is that I need two Repos: one for each schema with different authentication for each. That way each repo would be using their default schema for the user they are logged in as.

**Comment by vstavskyi** [comment]
Check [interesting discussion](https://github.com/elixir-ecto/ecto/issues/1942).

I've used @schema_prefix successfully.

```
defmodule Jamdb.OracleTest.Country do
  use Ecto.Schema
  import Ecto.Changeset
   
  @primary_key {:region_id, :float, autogenerate: false}
  @schema_prefix "hr"
  schema "countries" do
    field :country_id, :string
    field :country_name, :string
  end

  def changeset(value, params \\ %{}) do
    value
    |> cast(params, [:region_id, :country_id, :country_name])
  end  

end

defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo
  alias Jamdb.OracleTest.Country

  test "a" do
    changeset = Country.changeset(%Country{}, %{region_id: 1.0, country_id: "UA", country_name: "Ukraine" })
    assert %Country{} = TestRepo.insert_or_update!(changeset)
  end

  test "z" do
    assert [] = TestRepo.all(from(e in Country, where: e.region_id==1.0))
  end

end

```


```
16:37:22.016 [debug] QUERY OK db=11.8ms                                                                        
INSERT INTO hr.countries (country_id,country_name,region_id) VALUES (:1,:2,:3) ["UA", "Ukraine", 1.0]          
.
16:37:22.017 [debug] QUERY OK source="countries" db=0.6ms queue=0.1ms                                          
SELECT c0.region_id, c0.country_id, c0.country_name FROM hr.countries c0 WHERE (c0.region_id = 1.0) []   

```
