### ISSUE TITLE
Sproatically gettting error from (jamdb_oracle) lib/jamdb_oracle_ecto.ex:135

### ISSUE THREAD

**Issue by jasonandrewduncan** [erlangbureau/jamdb_oracle#36]
We are occasionally getting this error/stack trace. There does not seem to be any predictable pattern to it. 

  | ** (exit) an exception was raised:     ** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2         (logger) lib/logger/utils.ex:20: Logger.Utils.truncate_n(%Jamdb.Oracle.Query{statement: "SELECT p0.token, p0.web_user_id, p0.inserted_at FROM password_reset_tokens p0 WHERE (p0.token = :1)"}, 8031)         (logger) lib/logger/utils.ex:49: Logger.Utils.truncate_n_list/3         (logger) lib/logger/utils.ex:16: Logger.Utils.truncate/2         (logger) lib/logger.ex:581: Logger.bare_log/3         (ecto) lib/ecto/log_entry.ex:42: Ecto.LogEntry.log/1         (db_connection) lib/db_connection.ex:1178: DBConnection.log/6         (jamdb_oracle) lib/jamdb_oracle_ecto.ex:135: Ecto.Adapters.Jamdb.Oracle.Connection.execute/4         (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
-- | --

We are using the latest version of JamDB Ecto and using Ecto version "2.2.7".  Let me know if you need any additional information.

**Comment by vstavskyi** [comment]
Please try with this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/1919e8223d4d0e799d60724df362ab3434deb527)
