### ISSUE TITLE
Database credentials shown in error log

### ISSUE THREAD

**Issue by cedric5** [erlangbureau/jamdb_oracle#40]
I noticed that sometimes when the connection to the database timeouts all the database credentials are shown in the error log.
This could form a security risk.

> [error] Jamdb.Oracle (#PID<0.559.0>) failed to connect: ** (ErlangError) Erlang error: [timeout: 15000, password: '------', user: '------', port: ---, host: '------', service_name: '------]

**Comment by vstavskyi** [comment]
The driver implements the protocol. And it's not a security protocol.
I learned from @kagux that we can make a connection via ssh tunnel.
