### ISSUE TITLE
Run with Oracle RAC??

### ISSUE THREAD

**Issue by braulio** [erlangbureau/jamdb_oracle#42]
Run with Oracle RAC??

**Comment by vstavskyi** [comment]
Challenge accepted.

I'd like to start with a simple connection description without LOAD_BALANCE option.
Can you help me with that? For example, tcpdump of JDBC connection will be very useful.

**Comment by braulio** [comment]
What options should I use in tcpdump?

**Comment by vstavskyi** [comment]
-s 0 -w ooo.pcap will create pcap file, which will be opened using wireshark.

Are you able to connect to your rac with current driver like to standalone server?
If so please run `select rpad('*', 10000, '*') from dual;` and post that dump too.
 I'd like to check network packets sizes like we already did with @kagux  in[ this](https://github.com/erlangbureau/jamdb_oracle/issues/22) discussion. 
May be we'll catch something interesting.

**Comment by vstavskyi** [comment]
With this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/3fc7c1508e07c7a6b143e4f8f80a179850b1991e) I was able to connect to my test rac.
[rac.zip](https://github.com/erlangbureau/jamdb_oracle/files/1677771/rac.zip)
![virtualbox](https://user-images.githubusercontent.com/23114643/35569125-e71ba7c4-05d3-11e8-86d0-cee7d036522f.png)
![desktop](https://user-images.githubusercontent.com/23114643/35569135-eb11e85c-05d3-11e8-960a-577371b877ce.png)

**Comment by braulio** [comment]
which OTP are you using?

**Comment by vstavskyi** [comment]
19.3
