### ISSUE TITLE
When insert a '0.0' to Number(22,2) field, will meet a timeout error. 

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#43]
Version: 0.1.2
iex> map = [%{balance_total: 0.0, ....}]
iex> Repo.insert_all(QuickbookCsv, map)
[error] Jamdb.Oracle (#PID<0.287.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.316.0> timed out because it checked out the connection for longer than 15000ms

**Comment by vstavskyi** [comment]
Thanks,  it was a stupid mistake.
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/f254254ad11847d8e1b8eec6d8581ee1da4e34ab#diff-1ec314dda3f14e81a1ead2f73ac4aaa4R414)

**Comment by yukilau99** [comment]
Could you publish to Hex.pm?
