### ISSUE TITLE
Connection error without reason

### ISSUE THREAD

**Issue by AxelRHD** [erlangbureau/jamdb_oracle#44]
I got an error every time I use to connect do my OracleDB.

Command: `{:ok, conn} = Jamdb.Oracle.connect(hostname: "fqdn", port: 1521, database: "sid-name", username: "user", password: "secret", timeout: 15000)`

leads to the following error: `** (EXIT from #PID<0.257.0>) shell process exited with reason: [timeout: 15000, password: 'secret', user: 'user', port: 1521, host: 'fqdn', service_name:'sid-name']`

I also have to define port and timeout, because the default-values weren't used (got an error for missing parameters).

Oracle instantclient is installed and works properly.

Can't get anything out of the error-'description' above.

**Comment by vstavskyi** [comment]
@callback connect(opts :: Keyword.t) :: 
A keyword is a list of two-element tuples, thus
{:ok, conn} = Jamdb.Oracle.connect(**[** hostname: "fqdn", port: 1521, database: "sid-name", username: "user", password: "secret", timeout: 15000 **]**)

**Comment by AxelRHD** [comment]
Ok. Tried it with the [ ] brackets but still got exact the same error.

**Comment by vstavskyi** [comment]
Try supply connection details for your test database in config/test.exs and execute
mix test

**Comment by AxelRHD** [comment]
I don't use ecto, it's only a standard mix-project (also I'm still pretty new to Elixir). How the conf.exs has to look like for an implementation?

The last error seams to be matching. I thought the database is the SID (127.0.0.1:1521/SID)? Or is it an identifier of the tnsnames.ora?

**Comment by vstavskyi** [comment]
You can start with iex (Elixir’s interactive shell).
:database -Database service name or SID with colon as prefix

**Comment by vstavskyi** [comment]
`:database` Database service name or SID with colon as prefix

Mix project example:

mix.exs
```
...
  defp deps do
    [
      {:jamdb_oracle, "~> 0.1"}
    ]
  end
...
```
config/config.exs
```
use Mix.Config

env_file = "#{Mix.env}.exs"
if Path.join("config", env_file) |> File.exists? do
  import_config env_file
end
```
config/dev.exs
```
use Mix.Config

config :jamdb_oracle,
  username: "hr",
  password: "hr",
  hostname: "127.0.0.1",
  database: "orcl",
  port: 1521,
  timeout: 15000
```
lib/test.ex
```
defmodule Test do
 use Application
 
  def start(_type, _args) do
    opts = Application.get_all_env(:jamdb_oracle)
    {ok, conn} = Jamdb.Oracle.connect(opts)
    Jamdb.Oracle.query(conn, 'select 1+:1, sysdate, rowid from dual where 1=:1 ', [1]) |> IO.inspect
    Jamdb.Oracle.disconnect(:now,conn)
  end
end
```

**Comment by braulio** [comment]
I'm getting the same error.

** (EXIT from #PID<0.242.0>) shell process exited with reason: [timeout: 15000, password: 'THCPASS', user: 'THCUSER', port: 1521, host: '10.10.1.19', service_name: 'THC']

I checked the packages and have an ORA 01017 error but the username and password are correct.

0000   04 01 01 00 00 02 03 f9 00 00 00 00 00 00 00 00  ................
0010   00 00 00 00 00 00 00 00 00 04 00 00 33 4f 52 41  ............3ORA
0020   2d 30 31 30 31 37 3a 20 69 6e 76 61 6c 69 64 20  -01017: invalid 
0030   75 73 65 72 6e 61 6d 65 2f 70 61 73 73 77 6f 72  username/passwor
0040   64 3b 20 6c 6f 67 6f 6e 20 64 65 6e 69 65 64 0a  d; logon denied.

**Comment by vstavskyi** [comment]
Please post database release version.

**Comment by braulio** [comment]
NLSRTL 	                                                        11.2.0.4.0	Production
Oracle Database 11g Enterprise Edition 	11.2.0.4.0	64bit Production
PL/SQL 	                                                        11.2.0.4.0	Production
TNS for Linux: 	                                                11.2.0.4.0	Production

**Comment by vstavskyi** [comment]
#33 
Try to change password.

**Comment by vstavskyi** [comment]
finally
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/41ed8917bb993a1537ad40228c6ada471fb47c8b)
