### ISSUE TITLE
How to slow down re-connect attempts?

### ISSUE THREAD

**Issue by thomis** [erlangbureau/jamdb_oracle#45]
First of all thanks for creating jamdb_oracle. I've started to look into it for a Phoenix project with a potential use in a productive environment.

While I was testing I realised that when database is not reachable the driver is constantly trying to re-connect within a very short time.

The underlying DBConnection component has the concept of backoff_type (see [here](https://hexdocs.pm/db_connection/1.1.2/DBConnection.html#start_link/2)). Wondering if it is possible to pass parameter via the initial connection configuration in Phoenix.

I was thinking along these lines but that was not working:

```
# ./config/dev.exs
config :screening, Screening.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  hostname: "myhost.domain.com",
  port: 1521,
  database: "mydatabase",
  username: "a_user",
  password: "secret_password",
  parameters: [{:backoff_type, :exp}]. # or :rand or :exp_rand (which should be the default)
```

What I get is a lot of these errors and I'd like to slow down the connection attempts:

```
# console output
...
[error] Jamdb.Oracle (#PID<0.10491.0>) failed to connect: ** (ErlangError) Erlang error: {{:badmatch, {:error, :socket, :nxdomain}}, [{:jamdb_oracle, :init, 1, [file: 'src/jamdb_oracle.erl', line: 35]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
...
```

And yes, I am new to Elixir and the Phoenix Framework.

I am using Elixir 1.6.6 (compiled with OTP 20) and Phoenix v1.3.2

Thanks for every hint and help.

**Comment by vstavskyi** [comment]
Hi, @thomis 
Please check out [test](https://github.com/erlangbureau/jamdb_oracle/tree/test) branch.
New test version is based on [mssqlex](https://hex.pm/packages/mssqlex) and [mssql_ecto](https://hex.pm/packages/mssql_ecto).

**Comment by vstavskyi** [comment]
Hi again, @thomis
Please test last version 0.3.0 for Ecto 3.0

**Comment by thomis** [comment]
Hi @vstavskyi 
Thanks for getting back on this.

I was trying with following configuration/settings.

```
# mix.exs
{:jamdb_oracle, git: "https://github.com/erlangbureau/jamdb_oracle.git"}
```

```
# repo.ex
defmodule Oracle.Repo do
  use Ecto.Repo,
    otp_app: :oracle,
    adapter: Ecto.Adapters.Jamdb.Oracle
end
```

```
# dev.exs
config :oracle, Oracle.Repo,
  hostname: "a_hostname",
  port: 1521,
  database: "a_sid",
  username: "a_username",
  password: "a_password"
```

 I am using Elixir 1.7.4 (compiled with Erlang/OTP 21) and Phoenix 1.4.0.

Then I disconnected network to database by pulling cable (Wifi was off) and got this:

```
[error] GenServer #PID<0.410.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, :timeout}
    (jamdb_oracle) lib/jamdb_oracle.ex:220: Jamdb.Oracle.ping/1
    (db_connection) lib/db_connection/connection.ex:143: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:259: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:ping, #Reference<0.4158653208.2251161601.210311>, %Jamdb.Oracle{cursors: nil, mode: :idle, pid: #PID<0.416.0>}}}
State: {Jamdb.Oracle, %Jamdb.Oracle{cursors: nil, mode: :idle, pid: #PID<0.416.0>}}
[error] Jamdb.Oracle (#PID<0.695.0>) failed to connect: ** (DBConnection.ConnectionError) {{:case_clause, {:error, :socket, :nxdomain}}, [{:jamdb_oracle, :init, 1, [file: 'src/jamdb_oracle.erl', line: 35]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
[info] Application oracle exited: shutdown
```

It took a couple of seconds until it detects the connection issue which is ok. So, not fast re-connect attempts. Unfortunately, after plugging back in the cable the complete phoenix app did not recover anymore. Not sure if I have to provide more configuration options.

Any idea?

Thanks a lot for all the help and for the time looking into this.

thomis

**Comment by vstavskyi** [comment]
Try to increase values of  parameters `timeout`, `pool_timeout`, `idle_interval`.
The timeout for queries, ping queries also, is 15000, try to set 60000.
The ping interval in dbconnection 2.0 is 1000 (1 sec), I've set 1000000 for testing purpose.
