### ISSUE TITLE
** (ArgumentError) cannot load `340.0` as type :integer

### ISSUE THREAD

**Issue by yukilau99** [erlangbureau/jamdb_oracle#46]
When count the subquery meet type error. 

count_customers=from( c in CountryGroup, left_join: cu in assoc(c, :customers), group_by: c.countrygroup_id, select: %{countrygroup_id: c.countrygroup_id, count: count(cu.customer_id) })

q =    from c in CountryGroup,
    join: counts in subquery(count_customers),
    on: counts.countrygroup_id== c.countrygroup_id,
    select_merge: %{count: counts.count},
    where: like(fragment("upper(countrygroup_name)"), ^countrygroupname) and like(fragment("upper(countrygroup_city)"), ^countrygroupcity)

Repo.all q

error:
iex(10)> Repo.all q                                                                                                                                
[debug] QUERY ERROR source="country_groups" db=4.8ms decode=9.1ms
SELECT c0.countrygroup_id, c0.countrygroup_city, c0.countrygroup_name, c0.country_id, c0.sys_user_id, c0.inserted_at, c0.updated_at, s1.count FROM country_groups c0 JOIN (SELECT c0.countrygroup_id countrygroup_id, count(c1.customer_id) count FROM country_groups c0 LEFT JOIN country_group_customers c2 ON c2.country_group_id = c0.countrygroup_id LEFT JOIN customers c1 ON c2.customer_id = c1.customer_id GROUP BY c0.countrygroup_id) s1 ON s1.countrygroup_id = c0.countrygroup_id WHERE ((upper(countrygroup_name) LIKE :1) AND (upper(countrygroup_city) LIKE :2)) ["%%", "%%"]
** (ArgumentError) cannot load `340.0` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:320: Ecto.Repo.Queryable.load!/5
    (ecto) lib/ecto/repo/queryable.ex:262: Ecto.Repo.Queryable.process/5
    (ecto) lib/ecto/repo/queryable.ex:308: anonymous fn/5 in Ecto.Repo.Queryable.process_kv/5
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:242: Ecto.Repo.Queryable.process/5
    (ecto) lib/ecto/repo/queryable.ex:194: Ecto.Repo.Queryable.process/5
    (ecto) lib/ecto/repo/queryable.ex:174: Ecto.Repo.Queryable.preprocess/5
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (jamdb_oracle) lib/jamdb_oracle.ex:188: DBConnection.Query.Jamdb.Oracle.Query.decode/3
    (db_connection) lib/db_connection.ex:1019: DBConnection.decode/6
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:152: Ecto.Adapters.Jamdb.Oracle.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4

Seems like the issue met before.

**Comment by yukilau99** [comment]
Can help?

**Comment by vstavskyi** [comment]
Hi!

My one-to-many assoc example without select_merge expr.
**Important!** For :integer primary keys I've set ID and REGION_ID datatypes as NUMBER(*,0).


CREATE TABLE "REGION
   (**"ID" NUMBER(*,0)**, 
	"REGION_NAME" VARCHAR2(25 BYTE)
   );

CREATE TABLE "COUNTRY" 
   ("COUNTRY_ID" CHAR(2 BYTE), 
	"COUNTRY_NAME" VARCHAR2(40 BYTE), 
	**"REGION_ID" NUMBER(*,0)**, 
	"ID" NUMBER(*,0)
   );
   
defmodule Jamdb.OracleTest.Region do
  use Ecto.Schema
  import Ecto.Changeset
   
  schema "region" do
    field :region_name, :string
    **has_many :country, Jamdb.OracleTest.Country**
  end
end

defmodule Jamdb.OracleTest.Country do
  use Ecto.Schema
  import Ecto.Changeset
   
  schema "country" do
    field :country_id, :string
    field :country_name, :string
    **belongs_to :region, Jamdb.OracleTest.Region**
  end
end

defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo
  alias Jamdb.OracleTest.Country
  alias Jamdb.OracleTest.Region

  test "a" do
     count_subquery = from r in Region, 
      join: c in assoc(r, :country), 
      group_by: r.id, 
     select: %{region_id: r.id, count: count(c.region_id)}
     assert [] = TestRepo.all from c in Country, 
     join: counts in subquery(count_subquery), 
     on: counts.region_id==c.region_id, 
     **select**: %{count: counts.count}, 
     where: like(c.country_id,"U%") 
  end
end

> SELECT s1.count FROM country c0 JOIN (SELECT r0.id region_id, count(c1.region_id) count FROM region r0 JOIN country c1 ON c1.region_id = r0.id GROUP BY r0.id) s1 ON s1.region_id = c0.region_id WHERE (c0.country_id LIKE 'U%') []
> 
> [%{count: 5}, %{count: 9}, %{count: 9}]
