### ISSUE TITLE
Error decoding too long fields

### ISSUE THREAD

**Issue by fcabouat** [erlangbureau/jamdb_oracle#49]
Hi,

I've got this error when querying a big varchar column constructed from a wm_concat() function (temporary table).

** (DBConnection.ConnectionError) [{:jamdb_oracle_tns_decoder, :decode_chr, 2, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 502]}, {:jamdb_oracle_tns_decoder, :decode_data, 2, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 400]}, {:jamdb_oracle_tns_decoder, :decode_rxd, 6, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 342]}, {:jamdb_oracle_tns_decoder, :decode_token, 3, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 182]}, {:jamdb_oracle_conn, :handle_resp, 4, [file: 'src/jamdb_oracle_conn.erl', line: 232]}, {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 43]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}]
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:175: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (fetch_sil) lib/fetch_sil.ex:18: FetchSil.hello/0 

There seems to be an invalid character in my data ? I can query it with Squirrel or SQLDeveloper without issues. When I do an aggressive substr() on the field (truncate the varchar at 50), thus probably eliminating the unwanted char, I don't suffer from the issue anymore.

Cheers / thanx a lot for this library.

**Comment by fcabouat** [comment]
Uhm, sorry, seems I didn't investigate enough before posting an issue. Seems the difference doesn't rely only in count() vs wm_concat() but the error has more to do with the shape of data produced by the wm_concat aggregate function (too large column ?).

**Comment by fcabouat** [comment]
This gets super weird as I tried to troubleshoot the request/column/data in iex :

> OracleTestRepo.query("SELECT DISTINCT SUBSTR(cluster_typbojs, 1, 30) || SUBSTR(cluster_typobjs,29 , 1990) as t FROM structure_tables")

The request sometimes returns OK, sometimes returns KO

**Comment by vstavskyi** [comment]
It looks like #22 issue.

So, please add  `io:format` in jamdb_oracle_conn.erl and execute select.

```
recv(Socket, Acc, Data) ->
    Tout = 500,
    case sock_recv(Socket, 0, Tout) of
        {ok, NetworkData} ->
            io:format("~p~n", [{byte_size(Acc),byte_size(NetworkData),byte_size(Data)}]),
            recv(Socket, Tout, <<Acc/bits, NetworkData/bits>>, Data);
        {error, timeout} ->
            {ok, ?TNS_DATA, Data};
        {error, Reason} ->
            {error, socket, Reason}
    end.
```
`select a,a,a,a from (select rpad('a',4000,'a') a from dual)
`

Output example:

{1460,1460,0}
{2920,1460,0}
{4380,1460,0}
{5840,1460,0}
{7300,1460,0}
{649,1460,8101}
{2109,1460,8101}
{3569,1460,8101}
{5029,1460,8101}
{6489,1460,8101}
{7949,293,8101}

**Comment by fcabouat** [comment]
Example of an OK request :
iex(17)> :jamdb_oracle.sql_query(pid, "select a,a,a,a from (select rpad('a',4000,'a') a from dual)" |> to_charlist)
{1460,1460,0}
{909,1460,2001}
{358,363,4002}
{721,1460,4002}
{170,1460,6003}
{1630,1460,6003}
{1079,1084,8004}
{152,1460,10005}
{1612,1460,10005}
{1061,1460,12006}
{510,1460,14007}
{1970,391,14007}
{:ok,
 [
   {:result_set, ["A", "A", "A", "A"], [],
    [
      ['aaaaaaaaaaaa ...

--
KO requests :
iex(18)> :jamdb_oracle.sql_query(pid, "select a,a,a,a from (select rpad('a',4000,'a') a from dual)" |> to_charlist)
{1460,551,0}
{:error, :local,
 [
   {:jamdb_oracle_tns_decoder, :decode_chr, 2,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 504]},
   {:jamdb_oracle_tns_decoder, :decode_data, 2,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 402]},
   {:jamdb_oracle_tns_decoder, :decode_rxd, 6,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 336]},
   {:jamdb_oracle_tns_decoder, :decode_token, 3,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 181]},
   {:jamdb_oracle_conn, :handle_resp, 4,
    [file: 'src/jamdb_oracle_conn.erl', line: 232]},
   {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 43]},
   {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}
 ]}

{1366,645,0}
{:error, :local,
 [
   {:jamdb_oracle_tns_decoder, :decode_chr, 2,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 504]},
   {:jamdb_oracle_tns_decoder, :decode_data, 2,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 402]},
   {:jamdb_oracle_tns_decoder, :decode_rxd, 6,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 336]},
   {:jamdb_oracle_tns_decoder, :decode_token, 3,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 181]},
   {:jamdb_oracle_conn, :handle_resp, 4,
    [file: 'src/jamdb_oracle_conn.erl', line: 232]},
   {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 43]},
   {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}
 ]}

**Comment by vstavskyi** [comment]
First, we have to try to add the magic number in guard expression in jamdb_oracle.hrl.
8111(16#1FAF), according to my dump, was already added.
Maybe 8004(16#1F44) is yours. 
Captured packets in pcap format could be helpful.
Do you have such file?

```
-define(IS_PACKET_SIZE(PacketSize),
    PacketSize =:= 8155;
    PacketSize =:= 8111;
    PacketSize =:= 8004
).

```

**Comment by fcabouat** [comment]
Hi, I'm quite a noob regarding network programming/security and I wouldn't feel confident sanitizing the pcap file correctly enough so I could upload it publicly without leaking passwords, IPs, etc.

I removed io:format and added -define(IS_PACKET_SIZE(PacketSize),
    PacketSize =:= 8155;
    PacketSize =:= 8111;
    PacketSize =:= 8014
).

I still get the error every few requests.

![wireshark3](https://user-images.githubusercontent.com/17034829/45564302-4d629180-b850-11e8-84bf-6c1c0adca780.png)
![wireshark4](https://user-images.githubusercontent.com/17034829/45564287-420f6600-b850-11e8-99f8-466f45bf26d5.png)

**Comment by vstavskyi** [comment]
![45564287-420f6600-b850-11e8-99f8-466f45bf26d5](https://user-images.githubusercontent.com/23114643/45574907-2b7e0480-b87a-11e8-9475-e683aebb4a87.png)

If 2011(16#07DB) is present in other packets, then we add 10 (header size) to 2011 and receive 2021.
Please try this number.

`PacketSize =:= 2021`

You don't have to upload all packets, only response after select request.

The full response must contain (4000*4/2000) 8-9 packets.

For me it's very unusual, because I receive (4000*4/8000) 2-3 packets.

**Comment by vstavskyi** [comment]
Now 8192 value is used for client-side SDU size.
I figured out that if server-side DEFAULT_SDU_SIZE parameter in `sqlnet.ora` less then 8192
then decoding packets doesn't work properly.

I'll try to fix it soon.

**Comment by vstavskyi** [comment]
Please test current version with latest commits.

**Comment by fcabouat** [comment]
I can't reproduce anymore / seems all good.

Thank you very much!
