### ISSUE TITLE
Oracle Client

### ISSUE THREAD

**Issue by wahmedswl** [erlangbureau/jamdb_oracle#51]
Hi, Is this driver works without Oracle Client or it need to be installed for this driver to work. JDBC or ODP.Net Managed driver work without Oracle Client, so is this driver depend on it or not.

Thanks

**Comment by vstavskyi** [comment]
Yes, It works without Oracle Client on Linux,Mac,Windows.

**Comment by wahmedswl** [comment]
@vstavskyi thanks for your quick response 👍
