### ISSUE TITLE
Dep poison has invalid version ~> 2.2 or ~> 3.0

### ISSUE THREAD

**Issue by francescm** [erlangbureau/jamdb_oracle#54]
Erlang/OTP 21 [erts-10.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

$ rebar3 new app welcome_jambd_oracle
$ cd welcome_jambd_oracle
$ vim rebar3.config
$ cat rebar3.config
{erl_opts, [debug_info]}.
{deps, [{jamdb_oracle, "0.3.0"}]}.

{shell, [
  % {config, "config/sys.config"},
    {apps, [welcome_jambd_oracle]}
]}.
$ rebar3 compile
===> Verifying dependencies...
===> Fetching jamdb_oracle ({pkg,<<"jamdb_oracle">>,<<"0.3.0">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/jamdb_oracle-0.3.0.tar is up to date, reusing it
===> Fetching ecto_sql ({pkg,<<"ecto_sql">>,<<"3.0.3">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/ecto_sql-3.0.3.tar is up to date, reusing it
===> Fetching jose ({pkg,<<"jose">>,<<"1.8.4">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/jose-1.8.4.tar is up to date, reusing it
===> Fetching base64url ({pkg,<<"base64url">>,<<"0.0.1">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/base64url-0.0.1.tar is up to date, reusing it
===> Fetching db_connection ({pkg,<<"db_connection">>,<<"2.0.3">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/db_connection-2.0.3.tar is up to date, reusing it
===> Fetching ecto ({pkg,<<"ecto">>,<<"3.0.5">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/ecto-3.0.5.tar is up to date, reusing it
===> Fetching mariaex ({pkg,<<"mariaex">>,<<"0.9.1">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/mariaex-0.9.1.tar is up to date, reusing it
===> Fetching postgrex ({pkg,<<"postgrex">>,<<"0.14.1">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/postgrex-0.14.1.tar is up to date, reusing it
===> Fetching telemetry ({pkg,<<"telemetry">>,<<"0.2.0">>})
===> Version cached at /Users/francesco/.cache/rebar3/hex/hexpm/packages/telemetry-0.2.0.tar is up to date, reusing it
===> Dep poison has invalid version ~> 2.2 or ~> 3.0

welcome_jambd_oracle
edit welcome_jambd_oracle/rebar.config to add:

**Comment by vstavskyi** [comment]
The mix.exs file from ecto package contains this complex condition
`{:poison, "~> 2.2 or ~> 3.0", optional: true},`

For mix projects elixir Version module is used to check deps
```
iex(1)> Version.parse_requirement("~> 2.2 or ~> 3.0")
{:ok, #Version.Requirement<~> 2.2 or ~> 3.0>}
iex(2)> Version.parse_requirement("~> 2.2")          
{:ok, #Version.Requirement<~> 2.2>}
```

But, for rebar3 projects in rebar_packages.erl  valid_vsn function is used

```
valid_vsn(Vsn) ->
    %% Regepx from https://github.com/sindresorhus/semver-regex/blob/master/index.js
    SemVerRegExp = "v?(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))?"
        "(-[0-9a-z-]+(\\.[0-9a-z-]+)*)?(\\+[0-9a-z-]+(\\.[0-9a-z-]+)*)?",
    SupportedVersions = "^(>=?|<=?|~>|==)?\\s*" ++ SemVerRegExp ++ "$",
    re:run(Vsn, SupportedVersions, [unicode]) =/= nomatch.
```
```
>io:format("~p~n",[valid_vsn("~> 2.2")]).
true
>io:format("~p~n",[valid_vsn("~> 2.2 or ~> 3.0")]).
false
```
So,for now, complex conditions in mix.exs are not compatible with rebar3.
Use the mix
$mix new welcome_jambd_oracle --sup

**Comment by francescm** [comment]
Good, fine with me.
