### ISSUE TITLE
Error "'ORA-01003: no statement parsed'"

### ISSUE THREAD

**Issue by epilgrim** [erlangbureau/jamdb_oracle#55]
I'm facing an issue where my repo stops working when there is a schema change on the DB.
Every single query after the schema change returns the following error:
```
** (exit) an exception was raised:
2018-12-19T15:31:53.374709+00:00 app[web.2]: ** (DBConnection.ConnectionError) 'ORA-01003: no statement parsed\n'
2018-12-19T15:31:53.374710+00:00 app[web.2]: (ecto_sql) lib/ecto/adapters/sql.ex:595: Ecto.Adapters.SQL.raise_sql_call_error/1
2018-12-19T15:31:53.374712+00:00 app[web.2]: (ecto_sql) lib/ecto/adapters/sql.ex:528: Ecto.Adapters.SQL.execute/5
2018-12-19T15:31:53.374713+00:00 app[web.2]: (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
2018-12-19T15:31:53.374715+00:00 app[web.2]: (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```
And it is only fixed after all the connections are restarted (As i'm on heroku, the fix is to restart the processes.)

The question is, should the driver do something in this case? 
Should I manually monitor for this kind of errors and force a repo stop and start?

Do you have any prior knowledge of this?

**Comment by vstavskyi** [comment]
Driver's keeping prepared statements. When number of statements is 127, driver's closing them to avoid ORA-01000 maximum open cursors exceeded error.

```
218   send_req(reset, #oraclient{cursors=Cursors} = State, Tout) ->
219      handle_req(pig, State, {tran, ?TTI_PING}, Tout),

274   case get_result(Auto, DefCol, {LCursor, Cursor, RowFormat}, Cursors) of
275      {reset, _} -> send_req(reset, State, Tout);

313   case length(Acc) > 127 of
314      true when Auto =:= 1 -> {reset, DefCol};
```

I can catch error 1003  and close that prepared statement and then you can re-run it without reconnect or analyze response and don't re-run.
And I can add internal command 'RESET' for closing all old prepared statements manually.
What do you think?

After ALTER TABLE ... RENAME COLUMN AAA TO BBB I just recieved ORA-00904 invalid identifier.
What has been changed?

**Comment by epilgrim** [comment]
After more digging i've found that the following errors appeared before the "no statement parsed":

`** (DBConnection.ConnectionError) 'ORA-04045: errors during recompilation/revalidation of COMPANY.PROJECT_CURRENT_BIDS_V\nORA-16000: database open for read-only access\n'`
`** (DBConnection.ConnectionError) 'ORA-04068: existing state of packages has been discarded\nORA-04065: not executed, altered or dropped function\n'`

I do not control the changes to the db, but I can ask the ops team what was the exact change this time. So far the only thing I know is that they were going to change a column.

A bit more context:
I'm querying a view that mixes together several tables.
There is a fair amount of data being transferred, sometimes spanning several seconds (up to 10 seconds is not unheard off. Sporadically up to 30 seconds, but that is usually due to network).
There is no synchronization whatsoever between the proceses that run the queries and the team that runs the ops of the db.

I wouldn't mind if current query / current set of queries blow up. I have retry mechanisms in place.

**Comment by vstavskyi** [comment]
ORA-01003 errors must disappear after this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/974c5ac3d8d351291f225fd98bf746ee886b184d).

**Comment by epilgrim** [comment]
hey @vstavskyi I haven't seen the errors for a while already. I think this ticket can be safely closed.
Thanks for your help!
