### ISSUE TITLE
batch insert could not handle maps

### ISSUE THREAD

**Issue by yuejw** [erlangbureau/jamdb_oracle#56]
It failed when I tried to exec a batch insert with a list of maps like this:

`jamdb_oracle:sql_query(Conn, {batch, "insert .... values (:field1, :field2)",  [#{field1 =>1, field2 =>2}, #{field1 =>1, field2 =>2}]}).`

Maybe we should change jamdb_oracle/src/jamdb_oracle_conn.erl:230 to

`send_req(exec, State, {Query, get_param(Data, Bind, []), [get_param(Data, B, []) || B <- Batch]});`

thank you.

https://github.com/erlangbureau/jamdb_oracle/blob/69296a19fb124d8d29116329cf84e694353e318f/src/jamdb_oracle_conn.erl#L227-L240

**Comment by yuejw** [comment]
the error:

`47> jamdb_oracle:sql_query(Conn, {batch, SQL, [Txn,Txn2]}).
{error,local,
       [{jamdb_oracle_tns_encoder,encode_token,
                                  [#{activate_Date => {2018,11,15},
                                     batch_Id => "045D06190120181115035943A6F6",
                                     business_Date => {2018,11,15},
                                     cd_Software_Id => 1007,data_Subtype => 2,data_Type => 81,
                                     device_Id => "02061904",device_Location => 619,
                                     device_Provider_Id => 0,line_Id => 6,location_Catalog => 6,
                                     num_In_Batch => 4,num_Of_Update => 2,
                                     old_Activate_Date => {2018,11,13},
                                     old_Version => 7,operator_Id => 0,
                                     settlement_Date => {2019,1,8},
                                     software_Batch_Num => 0,station_Id => 619,
                                     txn_Date_Time => {{2018,11,15},{3,33,1}},
                                     udsn => 11842,...},
                                   <<7>>],
                                  [{file,"src/jamdb_oracle_tns_encoder.erl"},{line,275}]},
        {jamdb_oracle_tns_encoder,encode_token,3,
                                  [{file,"src/jamdb_oracle_tns_encoder.erl"},{line,294}]},
        {jamdb_oracle_tns_encoder,encode_record,2,
                                  [{file,"src/jamdb_oracle_tns_encoder.erl"},{line,236}]},
        {jamdb_oracle_conn,send_req,3,
                           [{file,"src/jamdb_oracle_conn.erl"},{line,238}]},
        {jamdb_oracle_conn,sql_query,3,
                           [{file,"src/jamdb_oracle_conn.erl"},{line,95}]},
        {jamdb_oracle,handle_call,3,
                      [{file,"src/jamdb_oracle.erl"},{line,51}]}]}
`

fix and compile, it works:

`48> c(jamdb_oracle_conn).`
`Recompiling /mnt/d/jamdb_oracle/src/jamdb_oracle_conn.erl`
`{ok,jamdb_oracle_conn}`
`49> jamdb_oracle:sql_query(Conn, {batch, SQL, [Txn,Txn2]}).`
`{ok,[{affected_rows,2}]}`
`50> jamdb_oracle:sql_query(Conn, "rollback").`
`{ok,[]}`


here is two of those maps:

`51> Txn.`
`#{activate_Date => {2018,11,15},`
`  batch_Id => "045D06190120181115035943A6F6",`
`  business_Date => {2018,11,15},`
`  cd_Software_Id => 1006,data_Subtype => 2,data_Type => 81,`
`  device_Id => "02061904",device_Location => 619,`
`  device_Provider_Id => 0,line_Id => 6,location_Catalog => 6,`
`  num_In_Batch => 4,num_Of_Update => 2,`
`  old_Activate_Date => {2018,11,13},`
`  old_Version => 7,operator_Id => 0,`
`  settlement_Date => {2019,1,8},`
`  software_Batch_Num => 0,station_Id => 619,`
`  txn_Date_Time => {{2018,11,15},{3,33,1}},`
`  udsn => 11842,version_Number => 8,version_Type => 0}`
`52> Txn2.`
`#{activate_Date => {2018,11,15},`
`  batch_Id => "045D06190120181115035943A6F6",`
`  business_Date => {2018,11,15},`
`  cd_Software_Id => 1007,data_Subtype => 2,data_Type => 81,`
`  device_Id => "02061904",device_Location => 619,`
`  device_Provider_Id => 0,line_Id => 6,location_Catalog => 6,`
`  num_In_Batch => 4,num_Of_Update => 2,`
`  old_Activate_Date => {2018,11,13},`
`  old_Version => 7,operator_Id => 0,`
`  settlement_Date => {2019,1,8},`
`  software_Batch_Num => 0,station_Id => 619,`
`  txn_Date_Time => {{2018,11,15},{3,33,1}},`
`  udsn => 11842,version_Number => 8,version_Type => 0}`
`53>`

**Comment by vstavskyi** [comment]
Thank you, changes were commited.

Are you using  multiple inserts in elixir and ecto?
