### ISSUE TITLE
Unable to connect to local database

### ISSUE THREAD

**Issue by cruzfarfan** [erlangbureau/jamdb_oracle#58]
Hi,

I'm trying to use your adapter to connect to a local Oracle instance from an Elixir/Phoenix app. This is what I have in terms of configuration:

mix.exs:
  defp deps do
    [
      ...
      {:jamdb_oracle, git: "https://github.com/erlangbureau/jamdb_oracle.git"},

repo.ex:
defmodule Hello.Repo do
  use Ecto.Repo,
    otp_app: :hello,
    adapter: Ecto.Adapters.Jamdb.Oracle
end

dev.exs:
config :hello, Hello.Repo,
  hostname: "localhost",
  port: 1521,
  database: "XE",
  username: "cruz",
  password: "farfan"

After running "mix ecto.create", I get:
** (Mix) The database for Hello.Repo couldn't be created: false

But I'm able to connect from a CLI with: 
sqlplus cruz/farfan@//localhost:1521/XE

Any ideas what am I doing wrong?

Thank you,

Cruz

**Comment by OvermindDL1** [comment]
> ```
> After running "mix ecto.create", I get:
> ** (Mix) The database for Hello.Repo couldn't be created: false
> ```

That sounds more like it successfully connected but that it wasn't able to create the database, likely because of a permissions issue in the database.

> But I'm able to connect from a CLI with:
> sqlplus cruz/farfan@//localhost:1521/XE

Only thing command this does is connect, not create, and the mix command run of `mix ecto.create` actually creates the database in addition to connects.

**Comment by cruzfarfan** [comment]
Thanks for your quick reply. You're everywhere :)

After I logged in from sqlplus, I did:

GRANT CONNECT, RESOURCE, DBA TO cruz;
GRANT CREATE SESSION TO cruz;
GRANT ALL PRIVILEGES TO cruz;
GRANT UNLIMITED TABLESPACE TO cruz;

I've also just created a table from within sqlplus

**Comment by cruzfarfan** [comment]
Just tried with oracle "SYSTEM" account. Still the same error

**Comment by vstavskyi** [comment]
Hi @cruzfarfan

Use the Oracle Installer or sqlplus to create new database or to create new user. 
Examples of starting, mounting, stopping existing database you can find in [test/jamdb_oracle_dba.erl](https://github.com/erlangbureau/jamdb_oracle/blob/master/test/jamdb_oracle_dba.erl).

After creating the database and the user, just run your app "mix run ..."

**Comment by cruzfarfan** [comment]
OK. I don't know Erlang, but if I understood correctly, to use the adapter from Elixir, I should an external program to create the database user/schema first. Correct?

How about creating tables? Same process?

Thank you

**Comment by cruzfarfan** [comment]
Just did some tests and answered my own questions. OK. I'm happy to close the issue, but I'm hoping you guys add support for CREATE USER, etc.

Thank you
