### ISSUE TITLE
Query with starting new line character is not executing.

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#59]
While running the query string with Ecto.Adapters.SQL.query!, if the input query string has leading \n character the query is not executed.

When I removed the \n , the query is executing with results.

      {:jamdb_oracle, "~> 0.3.2"},

**Comment by vstavskyi** [comment]
quick [fix](https://github.com/erlangbureau/jamdb_oracle/commit/7f64267a670b5f185fce5ccc29d99983ae0182d0)

**Comment by vasumur** [comment]
Thanks @vstavskyi .

I have put in similar patch in my codebase. Let me know when this is available in master so I can remove my fix.

**Comment by vstavskyi** [comment]
The new version is available in Hex.
