### ISSUE TITLE
rebar.config is missing by execute mix deps.get

### ISSUE THREAD

**Issue by sho-suzuki** [erlangbureau/jamdb_oracle#6]
Hi I'm using elixir 1.2.5 and erlang 18.
my project's mix.exs as follows.
```elixir:mix.exs
defmodule Hoge.Mixfile do
  use Mix.Project
  def application do
    [mod: {Hoge, []},
     applications: [
       :jamdb_oracle
     ]
    ]
  end
  defp deps do
    [
      {:jamdb_oracle, "~> 0.0.1"}
   ]
  end
end
```
then I execute mix deps.get,mix compile and got error. 

```
Could not compile :jamdb_oracle, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
```

in my deps/jamdb_oracle dir, only some directory are avaliable.
please upload rebar.config to hex.pm, thank you.

**Comment by vstavskyi** [comment]
fixed

**Comment by sho-suzuki** [comment]
Thank you for your quick response!
I got rebar.config via hex.pm.

**Comment by vstavskyi** [comment]
Hello, @sho-suzuki.  I started to deploy Ecto adaper. Please, write issues and comment on it.
