### ISSUE TITLE
ConnectionError Running Stream Query

### ISSUE THREAD

**Issue by rzcastilho** [erlangbureau/jamdb_oracle#60]
I'm running a stream query and during the process, I'm disconnected a lot of times during the execution with the error below:

```
20:24:25.958 [error] Jamdb.Oracle (#PID<0.1691.0>) disconnected: ** (DBConnection.ConnectionError) [{:jamdb_oracle_tns_decoder, :decode_chr, 1, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 498]}, {:jamdb_oracle_tns_decoder, :decode_data, 2, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 402]}, {:jamdb_oracle_tns_decoder, :decode_rxd, 6, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 341]}, {:jamdb_oracle_tns_decoder, :decode_token, 3, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 181]}, {:jamdb_oracle_conn, :handle_resp, 4, [file: 'src/jamdb_oracle_conn.erl', line: 253]}, {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 51]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}]
```

I don't know if this is a network problem or a decode problem from driver, because I don't get this behavior with a JDBC for example.

Do you have some idea about this problem?

This is a long-running stream, the query returns about 8 million records.

Additional information:

1. Database Configuration

```
config :stream_legacy, StreamLegacy.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  url: "ecto://xxxxxx,
  timeout: :infinity,
  parameters: [autocommit: 0, fetch: 100, sdu: 16384]
```

2. Query Execution

```
def query(%{columns: columns, params: params}) do
    Repo.transaction(
      fn ->
        SQL.stream(Repo, QueryBuilder.select(), params, log: true)
        |> Stream.flat_map(fn %{rows: rows} -> rows end)
        |> Task.async_stream(fn row -> Enum.zip(columns, row) end)
        |> Task.async_stream(fn {:ok, row} -> Enum.into(row, %{}) end)
        |> Task.async_stream(&publish/1)
        |> Task.async_stream(&save_last_date/1)
        |> Stream.run()
      end,
      timeout: :infinity
    )
  end
```

3. Oracle Version
```
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE	12.1.0.2.0	Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production
```

Thank you!

**Comment by vstavskyi** [comment]
Sorry for the wait, but I think this is actually the same old network problem: [pull](https://github.com/erlangbureau/jamdb_oracle/pull/23) and [commit](https://github.com/erlangbureau/jamdb_oracle/commit/60f8d3b4bb51d6ada0cfe7b1147339d551e9ad52#diff-8c93136a5760d5319b22d9da0128053c)

In jamdb_oracle_conn.erl I changed 500 to 1000 and it worked for me.
```
recv(Socket, Length, Acc, Data) ->
    Tout = 500,
    case sock_recv(Socket, 0, Tout) of
        {ok, NetworkData} ->
            recv(Socket, Length, Tout, <<Acc/bits, NetworkData/bits>>, Data);
        {error, timeout} ->
            {ok, ?TNS_DATA, Data};
        {error, Reason} ->
            {error, socket, Reason}
    end.

```
The permanent solution still had to be found.

**Comment by vstavskyi** [comment]
You can use new parameter **read_timeout**
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/57487e9f0314865e6ee8eb20c83cabbc234dfe61)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/aadc5c78ebe1a54c5a647d8ce4c8dbf3d3d29b04)

 `parameters: [autocommit: 0, fetch: 100, sdu: 16384, read_timeout: 1000]`

**Comment by rzcastilho** [comment]
Thank you @vstavskyi, I think this new parameter will resolve the problem.

I'll make some tests.
