### ISSUE TITLE
Connect by servicename

### ISSUE THREAD

**Issue by francescm** [erlangbureau/jamdb_oracle#62]
How can we handle connection to a db with the servicename syntax:

"jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=tcp)(HOST=node01.example.org)(PORT=1521))(ADDRESS=(PROTOCOL=tcp)(HOST=node02.example.org)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=PROD_EXT)))"

using `jamdb_oracle` hash connection initializer?

**Comment by vstavskyi** [comment]
`:database` ecto parameter - Database service name or SID with colon as prefix.
So, without colon, it is Service Name.

Options LOAD_BALANCE and FAILOVER have not yet been realised. 
It's not that easy.

**Comment by francescm** [comment]
Thank you for clarification. Don't worry about LOAD_BALANCE and FAILOVER. I'm going to use a workaround.
