### ISSUE TITLE
clob decoding fails during decode_chr

### ISSUE THREAD

**Issue by sezaru** [erlangbureau/jamdb_oracle#65]
I have a query that is something like this:
`select r.report from TABLE r where r.id = 123132 and rownum <= 10`
`report` field is a clob which contains some text  which I think have some broken encoding (it's not my database, so I cannot fix that).

When I run that query, I get the expected 10 rows data correctly.
If I change rownum to 11 or simply remove it, then I get this error:
```
{:error, :local,
 [
   {:jamdb_oracle_tns_decoder, :decode_chr, 2,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 507]},
   {:jamdb_oracle_tns_decoder, :decode_clob, 1,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 664]},
   {:jamdb_oracle_tns_decoder, :decode_rxd, 6,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 343]},
   {:jamdb_oracle_tns_decoder, :decode_token, 3,
    [file: 'src/jamdb_oracle_tns_decoder.erl', line: 183]},
   {:jamdb_oracle_conn, :handle_resp, 4,
    [file: 'src/jamdb_oracle_conn.erl', line: 253]},
   {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 51]},
   {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}
 ]}
```

If I run this:
`select count(*) from TABLE r where r.id = 123132`
I get this:
`{:ok, [{:result_set, ["COUNT(*)"], [], [[{10}]]}]}`

Which means that the query only have 10 rows returned.

The first thing that I don't understand is that why changing rownum from 10 to 11 breaks the result (since the query only have 10 rows anyway, it should return the same data in both cases).

The issue seems to be in this part:
```
decode_chr(<<Length,Rest/bits>>, Acc) ->
    <<Data:Length/binary,Rest2/bits>> = Rest,
```

I changed it to this so I can see better what is happening:
```
decode_chr(<<Length,Rest/bits>>, Acc) ->
    io:format("~p ~p~n\n", [Length, Rest]),
    <<Data:Length/binary,Rest2/bits>> = Rest,
    Bla = decode_chr(Rest2, <<Acc/binary, Data/binary>>),
    io:format("~p~n", [Bla]),
    Bla.
```

I cannot show the full text because it is confidential data, but here is a part of it:
```
64 <<" mediolateral oblÃ­qua.Obtidas radiografias adicionais com afast@amento posterior dos implantesÂ  para melhor avaliaÃ§Ã£o do teci@do ">>

64 <<"amento posterior dos implantesÂ  para melhor avaliaÃ§Ã£o do teci@do ">>

64 <<"do ">>
```

As you can see, in the last row it returns Length as 64 but the string has only 3 characters. I'm not so sure why it is sending the wrong length there. I guess that maybe it has something to do to my encoding (you can see some wrong characters in the string above).

I will try to investigate more what is happening, but do you have any idea what can it be?

Thanks a lot!

**Comment by vstavskyi** [comment]
Try to change query
`select dbms_lob.substr(r.report, 4000, 1 ) r from TABLE r where r.id = 123132 and rownum <= 10`

It could be similar #60 issue.

**Comment by sezaru** [comment]
I tried to change it, only works with `dbms_lob.substr(r.report, 782, 1)` anything more than that trigger the error.
But with this query I do not get the full text since I'm only retrieving the first 782 characters.

Also, I tried to change Tout as show in issue #65 but it didn't help too.

**Comment by vstavskyi** [comment]
In ct[ test](https://github.com/erlangbureau/jamdb_oracle/blob/master/test/jamdb_oracle_SUITE.erl#L302)  ,however, decoding clobs in latin letters is working properly.

**Comment by vstavskyi** [comment]
Well, it's certainly network issue.
With clobs of ~500 bytes and **sdu** of 8192 bytes you need to set **fetch** parameter to 15 (500 * 15 < 8000). I think it's the best option.
Or, you can set new parameter **read_timeout** to 1000 (or higher)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/57487e9f0314865e6ee8eb20c83cabbc234dfe61)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/aadc5c78ebe1a54c5a647d8ce4c8dbf3d3d29b04)
