### ISSUE TITLE
Nxdomain error

### ISSUE THREAD

**Issue by gemantzu** [erlangbureau/jamdb_oracle#67]
Hey @vstavskyi , thanks for the lib.
I have been trying to connect from my linux box into my company's oracle database with your library, but I keep seeing the same error:
```elixir
** (EXIT from #PID<0.243.0>) shell process exited with reason: an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, :socket, :nxdomain}
        (jamdb_oracle) src/jamdb_oracle.erl:39: :jamdb_oracle.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
# Config

```elixir
config :jamdb_oracle,
  hostname: "database-srv",
  port: 1521,
  username: "username",
  password: "password",
  database: "orcl",
  timeout: 10000
```
By getting the configuration from the terminal (`Application.get_all_env(:jamdb_oracle)` and trying to connect (`Jamdb.Oracle.connect(opts)`) I see the above error.

Bear in mind that I can connect to this database through Ruby on Rails using the same configuration:

```ruby
development:
  <<: *default
  database: //(ip):1521/orcl
  username: username
  password: password
  encoding: ISO-8859-7
```

Any thoughts?
Thanks again.

**Comment by vstavskyi** [comment]
Hi,
nxdomain means "non-existent domain".
this is dns related problem. 
try to change short name to full name or ip address.
check inet:gethostbyname reply:
```
Eshell V9.3.3.6  (abort with ^G)
1> inet:gethostbyname("database-srv").
{ok,{hostent,"database-srv",[],inet,4,[{10,1,10,24}]}}

```

**Comment by gemantzu** [comment]
thanks for the quick reply @vstavskyi . Sorry if I keep bugging you, but I changed the hostname to the ip, and I received another unhandled error:
```elixir
** (EXIT from #PID<0.237.0>) shell process exited with reason: an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, :socket, :ehostunreach}
        (jamdb_oracle) src/jamdb_oracle.erl:39: :jamdb_oracle.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
It seems to try and do some work this time though, as the `Jamdb.Oracle.connect(opts)` command takes a while to finish.

Also, do you think it's in the scope of the project to handle these two errors? I could try and make a PR if yes.

**Comment by vstavskyi** [comment]
IMHO, driver doesn't need any extra features.
A database driver implements a protocol for a database connection, 
A connection pool maintains database connections and handles network errors.

**Comment by gemantzu** [comment]
Ok, thank you for your time and library :)
