### ISSUE TITLE
Ecto.Adapters.SQL.query error results don't match {:error, Exception.t()}

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#68]
As you can see below in my contrived example, the error exception results are not matching the expected

{:error, Exception.t()} as give in the Ecto.Adapters.SQL.query documentation https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#query/4

iex(13)> query
"select sysdate from dualxxx"
iex(14)> 
nil
iex(15)> Ecto.Adapters.SQL.query(MyOracleRepo, query)      
%DBConnection.ConnectionError{
  message: "'ORA-00942: table or view does not exist\\n'",
  severity: :error
}

The error is not of form {:error, Exception.t()}

**Comment by vstavskyi** [comment]
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/dadfe98a9a6c1b8a22ad3f11bf80b7340f3c4e91)

**Comment by vasumur** [comment]
And for this same test, we are getting different results, we are no longer getting the error message properly as before.

```

query = "select dummy from dualxxx"

Ecto.Adapters.SQL.query( MyOracleRepo, query)

 Error while executing query = "select dummy from dualxxx" for args = []. Error = {:error, %DBConnection.ConnectionError{message: "[]", severity: :error, reason: :error}}** (RuntimeError) Error while executing query = "select dummy from dualxxx" for args = []. Error = {:error, %DBConnection.ConnectionError{message: "[]", severity: :error, reason: :error}}

```
