### ISSUE TITLE
Decode issue

### ISSUE THREAD

**Issue by gemantzu** [erlangbureau/jamdb_oracle#69]
Hi @vstavskyi ! One more question, since I can't make this work yet. When I am querying for a list of products (I have created the schema module with the information I request), I get the following error:
```elixir
** (DBConnection.ConnectionError) [{:jamdb_oracle_tns_decoder, :decode_next, 1, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 263]}, {:jamdb_oracle_tns_decoder, :decode_token, 3, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 117]}, {:jamdb_oracle_tns_decoder, :decode_token, 3, [file: 'src/jamdb_oracle_tns_decoder.erl', line: 102]}, {:jamdb_oracle_conn, :handle_resp, 3, [file: 'src/jamdb_oracle_conn.erl', line: 254]}, {:jamdb_oracle, :handle_call, 3, [file: 'src/jamdb_oracle.erl', line: 51]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```
I think the problem is in charset, as I can't find "EL8ISO8859P7" in the jamdb_oracle.hrl file. Is that it or is there something else wrong you believe?

**Comment by vstavskyi** [comment]
Only basic [Oracle types](https://hexdocs.pm/jamdb_oracle/0.3.4/Ecto.Adapters.Jamdb.Oracle.html#module-primitive-types) are impemented.
What Oracle type is your list?

**Comment by gemantzu** [comment]
```elixir
  @primary_key false
  schema "schema_table" do
    field(:code, :string)
    field(:company, :string)
  end
```

I only have those two in my schema and they are strings. Sorry for the late response, I have been busy.

**Comment by vstavskyi** [comment]
:string is Ecto type. I meant Oracle types like VARCHAR2 or CLOB or something other.

If it's VARCHAR2 then look at #60 and #65 issues. Maybe you need to use `read_timeout` parameter because of network delays.

I added in  jamdb_oracle.hrl only common charsets. By default UTF-8 charset is used for client.

**Comment by gemantzu** [comment]
Ok. So that means I cannot make it work, since the database charset is ISO-8859-7 and that does not exist. Right? 

I don't get what you are talking about the oracle types, I have not defined them anywhere. It's quite possible I am missing the point and the correct usage of your library, so I am sorry if that's the case.

I defined that schema, and I am requesting data the same way I would if the db was in postgresql. Maybe that's the problem and I am supposed to use it differently?

**Comment by vstavskyi** [comment]
You can use it. UTF-8 will be used to decode strings. 
Migration and Creating Tables is not implemented, you can work with existsing tables.

**Comment by vstavskyi** [comment]
You can execute anything in begin ... end block
`Ecto.Adapters.SQL.query(YourApp.Repo, "BEGIN  CREATE TABLE ....   END;")`

**Comment by vstavskyi** [comment]
Character Sets Supported in Amazon RDS was added. Among them is EL8ISO8859P7.
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/2d34357b568a69d4c38135b8bc8e50c649a57e22)

**Comment by gemantzu** [comment]
Thank you @vstavskyi ! I hope to find some time today to check it out!

**Comment by gemantzu** [comment]
So, I am still getting the same error:
```elixir
iex(10)> Ecto.Adapters.SQL.query(OracleTest.Repo, "SELECT * FROM v$version;")

15:05:36.164 [debug] QUERY ERROR db=1.3ms
SELECT * FROM v$version; []
{:error,
 %DBConnection.ConnectionError{
   message: "'ORA-00911: invalid character\\n'",
   severity: :error
 }}
```

No matter what query I run, this is the result.

**Comment by vstavskyi** [comment]
try without last semicolon

**Comment by gemantzu** [comment]
Sorry for the inactivity on this, I have been on a car crash and I am still trying to find my pace. Thank you for your support in any case.
