### ISSUE TITLE
Query jamdb version at runtime

### ISSUE THREAD

**Issue by walter-weinmann** [erlangbureau/jamdb_oracle#73]
Is it possible to query the jamdb version at runtime - for Erlang as well as for Elixir?

**Comment by vstavskyi** [comment]
vsn attributes should be added to
jamdb_oracle.ex
```
defmodule Jamdb.Oracle do
  @vsn "0.3.6"
```
jamdb_oracle.erl
```
-module(jamdb_oracle).
-vsn("0.2.6").
```
and then Jamdb.Oracle.module_info  and  jamdb_oracle:module_info() would return vsn

**Comment by c-bik** [comment]
> vsn attributes should be added to
> jamdb_oracle.ex
> 
> ```
> defmodule Jamdb.Oracle do
>   @vsn "0.3.6"
> ```
> 
> jamdb_oracle.erl
> 
> ```
> -module(jamdb_oracle).
> -vsn("0.2.6").
> ```
> 
> and then Jamdb.Oracle.module_info and jamdb_oracle:module_info() would return vsn

alternatively (no need to implement anything)...
```erlang
ok = application:load(jamdb_oracle),
{ok, JamDBVsn} = application:get_key(jamdb_oracle, vsn)
```
to get it from 
https://github.com/erlangbureau/jamdb_oracle/blob/f9cdb3c540be23c93005ef2e5eb7f4b7cef772b7/src/jamdb_oracle.app.src#L3
