### ISSUE TITLE
[erlang] help to improve insert and select performance

### ISSUE THREAD

**Issue by c-bik** [erlangbureau/jamdb_oracle#76]
Hi,

I am trying to reduce the time to insert and select 100,000 rows with the following table:
```sql
describe ora_bench_table

Name          Null?    Type           
------------- -------- -------------- 
KEY           NOT NULL VARCHAR2(32)   
DATA                   VARCHAR2(4000) 
NO_PARTITIONS          NUMBER         
PARTITION_KEY          NUMBER(5)
```
Each row has 32 bytes of `KEY` and and 1024 bytes of `DATA`.

### `jamdb_test.erl`
```erlang
-module(jamdb_test).

-export([main/1]).

main(_) ->
  Opts = [
    {host, "localhost"},
    {port, 1521},
    {user, "scott"},
    {password, "tiger"},
    {service_name, "orclpdb1"},
    {app_name, "jamdb_test"}
  ],
  Chars =
    lists:seq($a, $b) ++ lists:seq($A, $B) ++ lists:seq($0, $9)
    ++ "[]{}+'\\/|\"*%&()=?$!-_:.,;<>",
  CharLen = length(Chars),
  InsertRows = [
    {
      [lists:nth(rand:uniform(CharLen), Chars) || _ <- lists:seq(1, 32)],
      [lists:nth(rand:uniform(CharLen), Chars) || _ <- lists:seq(1, 1024)]
    } || _ <- lists:seq(1, 100000)
  ],
  io:format("InsertRows ~p~n", [length(InsertRows)]),
  {ok, ConnRef} = jamdb_oracle:start_link(Opts),
  {ok,[]} = jamdb_oracle:sql_query(ConnRef, "COMOFF;"),
  io:format("Connected : ~p~n", [ConnRef]),
  {ok, [{affected_rows,0}]} = jamdb_oracle:sql_query(
    ConnRef, "TRUNCATE TABLE ora_bench_table"
  ),
  {DurationInsert, ok} = timer:tc(lists, foreach, [
    fun({Key, Data}) ->
      {ok, [{affected_rows,1}]} = jamdb_oracle:sql_query(
        ConnRef,
        {"INSERT INTO ora_bench_table (key, data) VALUES (:1, :2)", [Key, Data]}
      )
    end,
    InsertRows
  ]),
  InsertTotalSec = DurationInsert div 1000000,
  InsertMin = InsertTotalSec div 60,
  InsertSec = InsertTotalSec - InsertMin * 60,
  io:format(
    "~p rows inserted in ~2..0B:~2..0B (mm:ss)~n",
    [length(InsertRows), InsertMin, InsertSec]
  ),
  {DurationSelect, {ok,[{result_set, _, _, Rows}]}} = timer:tc(
    jamdb_oracle, sql_query,
    [ConnRef, "SELECT key, data FROM ora_bench_table"]
  ),
  SelectTotalSec = DurationSelect div 1000000,
  SelectMin = SelectTotalSec div 60,
  SelectSec = SelectTotalSec - SelectMin * 60,
  io:format(
    "~p rows selected in ~2..0B:~2..0B (mm:ss)~n",
    [length(Rows), SelectMin, SelectSec]
  ),
  ok = jamdb_oracle:stop(ConnRef),
  io:format("Disconnected!~n"),
  halt(0).
```

### OUTPUT
```sh
$ _build/default/bin/jamdb_test 
InsertRows 100000
Connected : <0.57.0>
100000 rows inserted in 01:31 (mm:ss)
100000 rows selected in 01:44 (mm:ss)
Disconnected!
```

I am wondering if there are any `jamdb_oracle` API settings / techniques I can try to improve this before trying partioning / multiprocess etc!

**I understand that performance is a very subjective topic and many other factor plays a role. I, however, in this case am only interested in the `jamdb_oracle` API use.**

TIA

**Comment by vstavskyi** [comment]
I think via JDBC you'll get the same pure result.
Like Tom said in [this](https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:1363403159158) answer, performance can be increased only by using batch inserts.

Inserts should look like this:
```
Batch = [[Key1, Data1],[Key2, Data2],[Key3, Data3],...]
{batch, "INSERT INTO ora_bench_table (key, data) VALUES (:1, :2)", Batch}
```

**Comment by c-bik** [comment]
@vstavskyi batching helped. Thanks a lot 👍
Insert is now three times faster. I however couldn't find any doc about `batch`. 

Can you also suggest anything similar to speed up SELECT as well?

I tried setting `FETCH` before select...
```erlang
{ok,[]} = jamdb_oracle:sql_query(ConnRef, {"FETCH", [100000]}),
```
but that made it worse (7 times slower)!

**Comment by vstavskyi** [comment]
Batch is mentioned briefly in hexdocs [here](https://hexdocs.pm/jamdb_oracle/Ecto.Adapters.Jamdb.Oracle.html#module-features).

With **read_timeout** parameter you can reduce waiting time while reading packet's parts from socket, but you must ensure that your network latency is low and bandwidth is high. Deafult value is 500, try 400, 300, 200, 100.

With **fetch** parameter you can optimize the number of packets that must be sent over the network. For short rows it will be most effectively. 
While selecting short fields, for example, 32 bytes + 11 bytes = 43 bytes in total with default **sdu** of 8192 bytes, you can set fetch parameter to 185 (43 * 185 < 8000). But while selecting long fields, for example, 32 bytes + 1024 bytes =1056 bytes, you need to set fetch parameter to 7 (1056 * 7 < 8000).

**Comment by c-bik** [comment]
> Batch is mentioned briefly in hexdocs [here](https://hexdocs.pm/jamdb_oracle/Ecto.Adapters.Jamdb.Oracle.html#module-features).

Thanks. Didn't check hex!

> With **read_timeout** parameter you can reduce waiting time while reading packet's parts from socket, but you must ensure that your network latency is low and bandwidth is high. Default value is 500, try 400, 300, 200, 100.

Does this matter/impact on "localhost" access?

> With **fetch** parameter you can optimize the number of packets that must be sent over the network. For short rows it will be most effectively.
> While selecting short fields, for example, 32 bytes + 11 bytes = 43 bytes in total with default **sdu** of 8192 bytes, you can set fetch parameter to 185 (43 * 185 < 8000). But while selecting long fields, for example, 32 bytes + 1024 bytes =1056 bytes, you need to set fetch parameter to 7 (1056 * 7 < 8000).

Ah this is quite useful. Oracle recommends [SDU shouldn't be more than MTU](http://www.rampant-books.com/t_oracle_sdu_tdu.htm). I will try 7 and report back here.

Thanks a lot @vstavskyi 👍

**Comment by c-bik** [comment]
FETCH|100000 rows selected in mm:ss
---|---
7|01:48
Default|01:35
1|02:34

So it seems that there aren't much difference between explicitly setting it to 7 vs using the default (not setting it). Performance starts to detoriate as I increased from 7 (as also indicated in your calculation).

Anyways, `batch` in insert helped a lot. Thanks again @vstavskyi.

Please feel free to close this if you don't have anything else for me to try for select.

**Comment by vstavskyi** [comment]
> Does this matter/impact on "localhost" access?

Yes, these are the same sockets. 

I suggest you start Wireshark and apply _tns_ filter. Then try various values for  **sdu**, **fetch**, **read_timeout**.
