### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by vasumur** [erlangbureau/jamdb_oracle#78]
While running a query using Ecto.Adapters.SQL.query, I am getting the below error.

{:error, %DBConnection.ConnectionError{message: "<<1, 10, 1, 10>>", severity: :error}}

The query is perfectly fine and I was able to run it perfectly fine in a few minutes. Anything we can do to improve this message to help me understand the underlying cause please. Appreciate your help.

Thanks.... Muralee

**Comment by vstavskyi** [comment]
With read_timeout parameter you can increase waiting time while reading packet's parts from socket.
Default value is 500, try 1000

**Comment by vasumur** [comment]
Thanks @vstavskyi. Appreciate the quick turnaround.

Appreciate if you could make the message readable, so it would help the wider audience.

**Comment by vstavskyi** [comment]
Please, describe you problem one more time with parts of code.

**Comment by vasumur** [comment]
As I mentioned above the read timeout increase helped with not getting the error.

I was wondering if the message can be any better readable.

What I got was 
{:error, %DBConnection.ConnectionError{message: "<<1, 10, 1, 10>>", severity: :error}}

**Comment by vstavskyi** [comment]
Error message was added in [jamdb_oracle.ex](https://github.com/erlangbureau/jamdb_oracle/blob/master/lib/jamdb_oracle.ex#L53)

**Comment by vasumur** [comment]
Thank you. This issue can be closed.
