### ISSUE TITLE
Batch `INSERT` and returning clause

### ISSUE THREAD

**Issue by llxff** [erlangbureau/jamdb_oracle#79]
Hello!

The client has two great features:

1. Batch `INSERT` query

`{:batch, "insert into tabl values (:1, :2, :3)", [[1, 2, 3],[4, 5, 6],[7, 8, 9]]}`

2. Returning clause

`{"insert into tabl values (tablid.nextval, sysdate) return id into :1", [{:out, :number}]}`

_(Examples are from the docs)_

But is it possible to use these two features together or it is not supported by Oracle?

Thank you!

**Comment by vstavskyi** [comment]
Hello!

I think BULK COLLECT Clause can be used only in PLSQL block.
But if you'll find JDBC example without PLSQL block, it would be imlemented within this driver.

[RETURNING INTO Clause with BULK COLLECT Clause](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-optimization-and-tuning.html#GUID-33749752-0DC6-4749-8A84-77CF3AC6FD6A)

**Comment by llxff** [comment]
@vstavskyi I see, thank you!
