### ISSUE TITLE
ORA-01013: user requested cancel of current operation

### ISSUE THREAD

**Issue by Defcoun** [erlangbureau/jamdb_oracle#85]
Sometimes I have errors in my queries 'ORA-01013: user requested cancel of current operation\n'.

I've found this article https://community.wegalvanize.com/s/article/ORA-01013-Error-when-trying-to-connect-to-an-Oracle-Database?language=en_US, but I don't know how to do it

Pls, help me :)

**Comment by vstavskyi** [comment]
Server returns several ORA errors, but this driver (and also odbc driver according to your link) can handle one error at a time.
Try to capture TNS traffic using Wireshark . You can see all the errors.

One more article
[http://www.dba-oracle.com/t_ora_01013_user_requested_cancel_of_current_operation.htm](http://www.dba-oracle.com/t_ora_01013_user_requested_cancel_of_current_operation.htm)

**Comment by vstavskyi** [comment]
Maybe this is timeout issue, like #60,  because of network delays.
Try to set  parameter **read_timeout** to 1000 (or higher).
