### ISSUE TITLE
ORA-01461: can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by balakumarrv** [erlangbureau/jamdb_oracle#86]
I am trying to insert text file data to BLOB column datatype ,but it throws below error

ORA-01461: can bind a LONG value only for insert into a LONG column

I am using **utl_raw.cast_to_raw(text file)**

Tried below way

utl_raw.cast_to_raw(substr(textfile,1,2000)) it is inserting upto 2000 characters.

can someone help with this ?

**Comment by vstavskyi** [comment]
#80 contains some answers

**Comment by vstavskyi** [comment]
`TABLE T1 ( B1 BLOB) `

`{"update T1 set B1=utl_raw.cast_to_raw(substr(rpad('a',4000,'a'),1,2000)) return B1 into :1 ",[{out,<<>>}]}`

pls, post your query with parameters
