### ISSUE TITLE
How to use prepared statement functionality ?

### ISSUE THREAD

**Issue by zhanghongtong** [erlangbureau/jamdb_oracle#87]
Hi, I want to use oracle insert preparedstatement, but I don't know how to use it, can you help me?

**Comment by vstavskyi** [comment]
Driver stores automatically IDs of all new executed statements with parameters and passes stored ID during next execution.
[jamdb_oracle_conn.erl#L319](https://github.com/erlangbureau/jamdb_oracle/blob/master/src/jamdb_oracle_conn.erl#L319)

So, just execute the same statement with new parameters  and Server runs it as preparedstatement.

BTW
Please test user and/or password containing CJK characters and give feedback.
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/d43ea094cf70b5cbfd149df30115799a78bd448d)

**Comment by zhanghongtong** [comment]
Hi, @vstavskyi 
Thank you for your reply. Sorry, I just contacted Oracle Database not long ago. I don't know what CJK characters are. What should I know?

**Comment by vstavskyi** [comment]
You can include multibyte characters in passwords.
> alter user scott identified by 虎
