### ISSUE TITLE
please don't log passwords

### ISSUE THREAD

**Issue by shribe** [erlangbureau/jamdb_oracle#90]
Currently the process for a connection maintains the password in its state forever, and on abnormal termination, such as a SQL error, the state including the password is logged.

I am not familiar with the Oracle protocol, so I don't know if there is any kind of re-auth that would require the password to be maintained after first use. If not, it could simply be cleared from state after use, [here](https://github.com/erlangbureau/jamdb_oracle/blob/c2af3f770e0d3f3152100bcaa814860a029beb2f/src/jamdb_oracle_conn.erl#L202). If so, then it could be stripped out in the `format_status` callback.

For example, this is [how postgrex does it](https://github.com/elixir-ecto/postgrex/commit/dac13a8a6e8d1666c36cee915866b44cfa119b0c).

**Comment by vstavskyi** [comment]
This can be done in .erl or .ex source files.

How do you create a database connection and create query?
Erlang?  Elixir DBConnection? Elixir Ecto?

Empty state is returned only once in .erl source file.
[ handle_error(socket, Reason, #oraclient{})](https://github.com/erlangbureau/jamdb_oracle/blob/c2af3f770e0d3f3152100bcaa814860a029beb2f/src/jamdb_oracle_conn.erl#L56)

Maybe empty state is needed after specific ORA errors?

**Comment by vstavskyi** [comment]
Please test master branch with last commits

**Comment by shribe** [comment]
I will do so today, thank you

--
Scott Ribe
***@***.***
https://www.linkedin.com/in/scottribe/
