### ISSUE TITLE
Data is incomplete. Pass :read_timeout as connection parameter.

### ISSUE THREAD

**Issue by 0xd61** [erlangbureau/jamdb_oracle#93]
I get a lot of data incomplete errors from my database (Oracle 11g) and I do not really know how to debug this issue. I've already increased the :read_timeout to 15 sec and still get this error.

My config is:
```
config :myapp, MyApp.Repo,
    url: System.fetch_env!("DATABASE_URL"),
    pool_size: String.to_integer(System.get_env("POOL_SIZE", "10")),
    parameters: [fetch: 100, sdu: 16384, read_timeout: 15000]
```

Is there a good way to debug this error? I'm pretty sure this has something to do with the database config, but I have no idea where to look.

**Comment by vstavskyi** [comment]
It's definitely a network problem.
Did you try to decrease fetch size?
If row size of resultset is ~2000, then set **fetch**  to 8 ( 2000 * 8 < 16384 ).

**Comment by vstavskyi** [comment]
Let's check network parameters.

Add io:format in jamdb_oracle_tns_decoder.erl

```
decode_packet(<<PacketSize:16, _PacketFlags:16, ?TNS_DATA, _Flags:8, 0:16, _DataFlags:16, Rest/bits>>, Length) ->
 io:format("~p~n", [{decode,PacketSize,Length,Length-PacketSize}]),
    BodySize = PacketSize-10,
    case Rest of
        <<PacketBody:BodySize/binary, Rest2/bits>> when PacketSize =:= Length-37; PacketSize =:= Length-81 ->
 io:format("~p~n", [{more,BodySize}]),
            {error, more, PacketBody, Rest2};
        <<PacketBody:BodySize/binary, Rest2/bits>> ->
            {ok, ?TNS_DATA, PacketBody, Rest2};
        _ ->
            {error, more}
    end;
```

Execute `select rpad('a',4000,'a') a, rpad('b',4000,'b') b, rpad('c',4000,'c') c, rpad('d',4000,'d') d from dual`

Look for 81 or 37 `{decode,8111,8192,81}`

**Comment by 0xd61** [comment]
Thanks for the reply. I made the changes and this was the result: `{decode,8155,8192,37}`

**Comment by vstavskyi** [comment]
OK. 
Default sdu was used. You can delete sdu parameter.
In jdbc driver read_timeout is 3000, I guess.
Try to set **read_timeout** parameter between 500 and 3000. 
Try to set **fetch** parameter between 10 and 100, depending on the average size of resultset's row.

**Comment by 0xd61** [comment]
Thanks for your help. Somehow I still get this error, but less frequent. I'm going to try different configs and see if the error goes away.

**Comment by 0xd61** [comment]
Thanks for your help. Somehow I still get this error, but less frequent. I'm going to try different settings and see if the error goes away.
