### ISSUE TITLE
Error on Connect - Possible Fix

### ISSUE THREAD

**Issue by mlh758** [erlangbureau/jamdb_oracle#95]
I think this is related to #92 since I got the error after pointing to the [scan vip](https://docs.oracle.com/en/database/oracle/oracle-database/18/riwin/about-scan-vip-addresses.html#GUID-795F99B3-FF71-4767-ADFD-351A6A29A4F8) for the cluster.

`connect/1` in `jamdb_oracle_conn.erl` was throwing an error and it looks like Opts was a tuple instead of a prop list. [Link](https://github.com/erlangbureau/jamdb_oracle/blob/a1638c4572c2a57e42304ff5d49a3ca6a3e51d90/src/jamdb_oracle_conn.erl#L32)

I changed the definition to:

```erl
-spec connect([env()]) -> empty_result().
connect({Key, Val, Opts}) ->
    NewOpts = [{Key, Val} | Opts],
    connect(NewOpts);

connect(Opts) when is_list(Opts) ->
    Tout        = proplists:get_value(timeout, Opts, ?DEF_TIMEOUT),
    connect(Opts, Tout).
```

since it seems like the message was a new value for options along with the old options. It _seems_ like it works now. I can PR this if it seems appropriate. Edit: Would probably need to update the type spec as well.

**Comment by mlh758** [comment]
Sorry for the spam...

```erl
-spec reconnect(state()) -> {ok, state()}.
reconnect(#oraclient{passwd=Passwd} = State) ->
    Passwd ! {get, self()},
    Pass = receive Reply -> Reply end,
    exit(Passwd, ok),
    {ok, InitOpts} = disconnect(State, 0),
    connect([{password, Pass} | InitOpts]).
```

This seems like the better fix, it makes dialyzer happy too.

**Comment by vstavskyi** [comment]
Fixed, thank you.

**Comment by mlh758** [comment]
Thank you!
