### ISSUE TITLE
`jamdb_oracle:start_link/1` return ok, but the connection failed

### ISSUE THREAD

**Issue by Rory-Z** [erlangbureau/jamdb_oracle#99]
Hi, 

When I run `jamdb_oracle:start_link/1`, i got `{ok, Pid}`, I thought I had a successful connection, but in fact, I didn't because I had set the wrong `sid` value

I noticed that `jamdb_oracle_conn:disconnect/1` would return the `{ok, ENV}`, which led me to mistake my connection for a successful connection

I think `jamdb_oracle_conn:disconnect/1` should return a more obvious hint so that I know that my connection has failed

**Comment by vstavskyi** [comment]
You can use  guard **when is_pid(Pid)**  in your app

**Comment by vstavskyi** [comment]
Please test this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/b8b72f09ca834cda727b681032a1c2562b5d3df6)

**Comment by Rory-Z** [comment]
> Please test this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/b8b72f09ca834cda727b681032a1c2562b5d3df6)

looks good for me

**Comment by vstavskyi** [comment]
Also, please test this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/20825056daa09c12a0e71d37ae04f23a1e3fe30f)
All strings are UTF-8 encoded binary already (or not?), 
So I replaced to_charlist (**:unicode.characters_to_list(string)**) with to_list (**:binary.bin_to_list(string)**)
